// Code generated by `go run ./cmd/codegen`. DO NOT EDIT.

package banyan

import (
	"context"
	evrblk "github.com/evrblk/evrblk-go"
	internal "github.com/evrblk/evrblk-go/internal"
	grpc "google.golang.org/grpc"
	insecure "google.golang.org/grpc/credentials/insecure"
	"log"
	"time"
)

type BanyanApi interface {
	CreateNamespace(ctx context.Context, request *CreateNamespaceRequest) (*CreateNamespaceResponse, error)
	ListNamespaces(ctx context.Context, request *ListNamespacesRequest) (*ListNamespacesResponse, error)
	GetNamespace(ctx context.Context, request *GetNamespaceRequest) (*GetNamespaceResponse, error)
	DeleteNamespace(ctx context.Context, request *DeleteNamespaceRequest) (*DeleteNamespaceResponse, error)
	UpdateNamespace(ctx context.Context, request *UpdateNamespaceRequest) (*UpdateNamespaceResponse, error)
	CreateWorkflow(ctx context.Context, request *CreateWorkflowRequest) (*CreateWorkflowResponse, error)
	ListWorkflows(ctx context.Context, request *ListWorkflowsRequest) (*ListWorkflowsResponse, error)
	GetWorkflow(ctx context.Context, request *GetWorkflowRequest) (*GetWorkflowResponse, error)
	DeleteWorkflow(ctx context.Context, request *DeleteWorkflowRequest) (*DeleteWorkflowResponse, error)
	UpdateWorkflow(ctx context.Context, request *UpdateWorkflowRequest) (*UpdateWorkflowResponse, error)
	CreateQueue(ctx context.Context, request *CreateQueueRequest) (*CreateQueueResponse, error)
	GetQueue(ctx context.Context, request *GetQueueRequest) (*GetQueueResponse, error)
	UpdateQueue(ctx context.Context, request *UpdateQueueRequest) (*UpdateQueueResponse, error)
	DeleteQueue(ctx context.Context, request *DeleteQueueRequest) (*DeleteQueueResponse, error)
	ListQueues(ctx context.Context, request *ListQueuesRequest) (*ListQueuesResponse, error)
	Dequeue(ctx context.Context, request *DequeueRequest) (*DequeueResponse, error)
	ReportStatus(ctx context.Context, request *ReportStatusRequest) (*ReportStatusResponse, error)
	RestartTasks(ctx context.Context, request *RestartTasksRequest) (*RestartTasksResponse, error)
	CreateSchedule(ctx context.Context, request *CreateScheduleRequest) (*CreateScheduleResponse, error)
	ListSchedules(ctx context.Context, request *ListSchedulesRequest) (*ListSchedulesResponse, error)
	GetSchedule(ctx context.Context, request *GetScheduleRequest) (*GetScheduleResponse, error)
	UpdateSchedule(ctx context.Context, request *UpdateScheduleRequest) (*UpdateScheduleResponse, error)
	DeleteSchedule(ctx context.Context, request *DeleteScheduleRequest) (*DeleteScheduleResponse, error)
	StartWorkflow(ctx context.Context, request *StartWorkflowRequest) (*StartWorkflowResponse, error)
	GetWorkflowRun(ctx context.Context, request *GetWorkflowRunRequest) (*GetWorkflowRunResponse, error)
	ListWorkflowRuns(ctx context.Context, request *ListWorkflowRunsRequest) (*ListWorkflowRunsResponse, error)
	DeleteWorkflowRun(ctx context.Context, request *DeleteWorkflowRunRequest) (*DeleteWorkflowRunResponse, error)
	CancelWorkflowRun(ctx context.Context, request *CancelWorkflowRunRequest) (*CancelWorkflowRunResponse, error)
	PauseWorkflowRun(ctx context.Context, request *PauseWorkflowRunRequest) (*PauseWorkflowRunResponse, error)
	ResumeWorkflowRun(ctx context.Context, request *ResumeWorkflowRunRequest) (*ResumeWorkflowRunResponse, error)
}
type BanyanGrpcClient struct {
	grpc   BanyanPreviewApiClient
	conn   *grpc.ClientConn
	signer evrblk.RequestSigner
}

var _ BanyanApi = &BanyanGrpcClient{}

func (c *BanyanGrpcClient) WithSigner(signer evrblk.RequestSigner) *BanyanGrpcClient {
	return &BanyanGrpcClient{
		conn:   c.conn,
		grpc:   c.grpc,
		signer: signer,
	}
}

func (c *BanyanGrpcClient) Close() {
	c.conn.Close()
}

func (c *BanyanGrpcClient) CreateNamespace(ctx context.Context, request *CreateNamespaceRequest) (*CreateNamespaceResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "CreateNamespace").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "CreateNamespace"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "CreateNamespace")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.CreateNamespace(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "CreateNamespace", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) ListNamespaces(ctx context.Context, request *ListNamespacesRequest) (*ListNamespacesResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "ListNamespaces").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "ListNamespaces"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "ListNamespaces")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.ListNamespaces(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "ListNamespaces", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) GetNamespace(ctx context.Context, request *GetNamespaceRequest) (*GetNamespaceResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "GetNamespace").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "GetNamespace"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "GetNamespace")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.GetNamespace(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "GetNamespace", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) DeleteNamespace(ctx context.Context, request *DeleteNamespaceRequest) (*DeleteNamespaceResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "DeleteNamespace").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "DeleteNamespace"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "DeleteNamespace")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.DeleteNamespace(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "DeleteNamespace", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) UpdateNamespace(ctx context.Context, request *UpdateNamespaceRequest) (*UpdateNamespaceResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "UpdateNamespace").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "UpdateNamespace"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "UpdateNamespace")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.UpdateNamespace(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "UpdateNamespace", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) CreateWorkflow(ctx context.Context, request *CreateWorkflowRequest) (*CreateWorkflowResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "CreateWorkflow").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "CreateWorkflow"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "CreateWorkflow")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.CreateWorkflow(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "CreateWorkflow", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) ListWorkflows(ctx context.Context, request *ListWorkflowsRequest) (*ListWorkflowsResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "ListWorkflows").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "ListWorkflows"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "ListWorkflows")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.ListWorkflows(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "ListWorkflows", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) GetWorkflow(ctx context.Context, request *GetWorkflowRequest) (*GetWorkflowResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "GetWorkflow").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "GetWorkflow"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "GetWorkflow")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.GetWorkflow(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "GetWorkflow", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) DeleteWorkflow(ctx context.Context, request *DeleteWorkflowRequest) (*DeleteWorkflowResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "DeleteWorkflow").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "DeleteWorkflow"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "DeleteWorkflow")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.DeleteWorkflow(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "DeleteWorkflow", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) UpdateWorkflow(ctx context.Context, request *UpdateWorkflowRequest) (*UpdateWorkflowResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "UpdateWorkflow").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "UpdateWorkflow"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "UpdateWorkflow")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.UpdateWorkflow(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "UpdateWorkflow", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) CreateQueue(ctx context.Context, request *CreateQueueRequest) (*CreateQueueResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "CreateQueue").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "CreateQueue"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "CreateQueue")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.CreateQueue(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "CreateQueue", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) GetQueue(ctx context.Context, request *GetQueueRequest) (*GetQueueResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "GetQueue").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "GetQueue"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "GetQueue")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.GetQueue(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "GetQueue", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) UpdateQueue(ctx context.Context, request *UpdateQueueRequest) (*UpdateQueueResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "UpdateQueue").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "UpdateQueue"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "UpdateQueue")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.UpdateQueue(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "UpdateQueue", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) DeleteQueue(ctx context.Context, request *DeleteQueueRequest) (*DeleteQueueResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "DeleteQueue").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "DeleteQueue"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "DeleteQueue")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.DeleteQueue(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "DeleteQueue", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) ListQueues(ctx context.Context, request *ListQueuesRequest) (*ListQueuesResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "ListQueues").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "ListQueues"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "ListQueues")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.ListQueues(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "ListQueues", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) Dequeue(ctx context.Context, request *DequeueRequest) (*DequeueResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "Dequeue").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "Dequeue"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "Dequeue")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.Dequeue(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "Dequeue", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) ReportStatus(ctx context.Context, request *ReportStatusRequest) (*ReportStatusResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "ReportStatus").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "ReportStatus"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "ReportStatus")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.ReportStatus(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "ReportStatus", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) RestartTasks(ctx context.Context, request *RestartTasksRequest) (*RestartTasksResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "RestartTasks").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "RestartTasks"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "RestartTasks")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.RestartTasks(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "RestartTasks", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) CreateSchedule(ctx context.Context, request *CreateScheduleRequest) (*CreateScheduleResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "CreateSchedule").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "CreateSchedule"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "CreateSchedule")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.CreateSchedule(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "CreateSchedule", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) ListSchedules(ctx context.Context, request *ListSchedulesRequest) (*ListSchedulesResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "ListSchedules").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "ListSchedules"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "ListSchedules")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.ListSchedules(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "ListSchedules", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) GetSchedule(ctx context.Context, request *GetScheduleRequest) (*GetScheduleResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "GetSchedule").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "GetSchedule"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "GetSchedule")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.GetSchedule(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "GetSchedule", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) UpdateSchedule(ctx context.Context, request *UpdateScheduleRequest) (*UpdateScheduleResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "UpdateSchedule").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "UpdateSchedule"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "UpdateSchedule")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.UpdateSchedule(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "UpdateSchedule", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) DeleteSchedule(ctx context.Context, request *DeleteScheduleRequest) (*DeleteScheduleResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "DeleteSchedule").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "DeleteSchedule"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "DeleteSchedule")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.DeleteSchedule(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "DeleteSchedule", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) StartWorkflow(ctx context.Context, request *StartWorkflowRequest) (*StartWorkflowResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "StartWorkflow").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "StartWorkflow"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "StartWorkflow")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.StartWorkflow(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "StartWorkflow", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) GetWorkflowRun(ctx context.Context, request *GetWorkflowRunRequest) (*GetWorkflowRunResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "GetWorkflowRun").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "GetWorkflowRun"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "GetWorkflowRun")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.GetWorkflowRun(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "GetWorkflowRun", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) ListWorkflowRuns(ctx context.Context, request *ListWorkflowRunsRequest) (*ListWorkflowRunsResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "ListWorkflowRuns").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "ListWorkflowRuns"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "ListWorkflowRuns")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.ListWorkflowRuns(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "ListWorkflowRuns", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) DeleteWorkflowRun(ctx context.Context, request *DeleteWorkflowRunRequest) (*DeleteWorkflowRunResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "DeleteWorkflowRun").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "DeleteWorkflowRun"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "DeleteWorkflowRun")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.DeleteWorkflowRun(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "DeleteWorkflowRun", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) CancelWorkflowRun(ctx context.Context, request *CancelWorkflowRunRequest) (*CancelWorkflowRunResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "CancelWorkflowRun").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "CancelWorkflowRun"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "CancelWorkflowRun")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.CancelWorkflowRun(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "CancelWorkflowRun", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) PauseWorkflowRun(ctx context.Context, request *PauseWorkflowRunRequest) (*PauseWorkflowRunResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "PauseWorkflowRun").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "PauseWorkflowRun"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "PauseWorkflowRun")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.PauseWorkflowRun(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "PauseWorkflowRun", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func (c *BanyanGrpcClient) ResumeWorkflowRun(ctx context.Context, request *ResumeWorkflowRunRequest) (*ResumeWorkflowRunResponse, error) {
	internal.TotalRequestsCounter.WithLabelValues("Banyan", "ResumeWorkflowRun").Inc()
	defer internal.MeasureSince(internal.RequestsDuration.WithLabelValues("Banyan", "ResumeWorkflowRun"), time.Now())

	signedCtx, err := c.signer.Sign(ctx, request, "Banyan", "ResumeWorkflowRun")
	if err != nil {
		return nil, err
	}

	resp, err := c.grpc.ResumeWorkflowRun(signedCtx, request, grpc.WaitForReady(true))
	if err != nil {
		internal.FailedRequestsCounter.WithLabelValues("Banyan", "ResumeWorkflowRun", internal.MetricLabelFromGrpcError(err)).Inc()
	}

	return resp, internal.ErrorFromRpcError(err)
}

func NewBanyanGrpcClient(address string, signer evrblk.RequestSigner) *BanyanGrpcClient {
	conn, err := grpc.NewClient(address, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	return &BanyanGrpcClient{
		conn:   conn,
		grpc:   NewBanyanPreviewApiClient(conn),
		signer: signer,
	}
}
