// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: proto/grackle/v1beta/api.proto

package grackle

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrackleApi_CreateNamespace_FullMethodName            = "/com.evrblk.grackle.v1beta.GrackleApi/CreateNamespace"
	GrackleApi_ListNamespaces_FullMethodName             = "/com.evrblk.grackle.v1beta.GrackleApi/ListNamespaces"
	GrackleApi_GetNamespace_FullMethodName               = "/com.evrblk.grackle.v1beta.GrackleApi/GetNamespace"
	GrackleApi_DeleteNamespace_FullMethodName            = "/com.evrblk.grackle.v1beta.GrackleApi/DeleteNamespace"
	GrackleApi_UpdateNamespace_FullMethodName            = "/com.evrblk.grackle.v1beta.GrackleApi/UpdateNamespace"
	GrackleApi_CreateSemaphore_FullMethodName            = "/com.evrblk.grackle.v1beta.GrackleApi/CreateSemaphore"
	GrackleApi_ListSemaphores_FullMethodName             = "/com.evrblk.grackle.v1beta.GrackleApi/ListSemaphores"
	GrackleApi_GetSemaphore_FullMethodName               = "/com.evrblk.grackle.v1beta.GrackleApi/GetSemaphore"
	GrackleApi_AcquireSemaphore_FullMethodName           = "/com.evrblk.grackle.v1beta.GrackleApi/AcquireSemaphore"
	GrackleApi_ReleaseSemaphore_FullMethodName           = "/com.evrblk.grackle.v1beta.GrackleApi/ReleaseSemaphore"
	GrackleApi_UpdateSemaphore_FullMethodName            = "/com.evrblk.grackle.v1beta.GrackleApi/UpdateSemaphore"
	GrackleApi_DeleteSemaphore_FullMethodName            = "/com.evrblk.grackle.v1beta.GrackleApi/DeleteSemaphore"
	GrackleApi_ListSemaphoreHolders_FullMethodName       = "/com.evrblk.grackle.v1beta.GrackleApi/ListSemaphoreHolders"
	GrackleApi_CreateSemaphoreLease_FullMethodName       = "/com.evrblk.grackle.v1beta.GrackleApi/CreateSemaphoreLease"
	GrackleApi_RevokeSemaphoreLease_FullMethodName       = "/com.evrblk.grackle.v1beta.GrackleApi/RevokeSemaphoreLease"
	GrackleApi_RefreshSemaphoreLease_FullMethodName      = "/com.evrblk.grackle.v1beta.GrackleApi/RefreshSemaphoreLease"
	GrackleApi_ListSemaphoreLeases_FullMethodName        = "/com.evrblk.grackle.v1beta.GrackleApi/ListSemaphoreLeases"
	GrackleApi_GetSemaphoreLease_FullMethodName          = "/com.evrblk.grackle.v1beta.GrackleApi/GetSemaphoreLease"
	GrackleApi_CreateWaitGroup_FullMethodName            = "/com.evrblk.grackle.v1beta.GrackleApi/CreateWaitGroup"
	GrackleApi_UpdateWaitGroup_FullMethodName            = "/com.evrblk.grackle.v1beta.GrackleApi/UpdateWaitGroup"
	GrackleApi_ListWaitGroups_FullMethodName             = "/com.evrblk.grackle.v1beta.GrackleApi/ListWaitGroups"
	GrackleApi_GetWaitGroup_FullMethodName               = "/com.evrblk.grackle.v1beta.GrackleApi/GetWaitGroup"
	GrackleApi_DeleteWaitGroup_FullMethodName            = "/com.evrblk.grackle.v1beta.GrackleApi/DeleteWaitGroup"
	GrackleApi_AddJobsToWaitGroup_FullMethodName         = "/com.evrblk.grackle.v1beta.GrackleApi/AddJobsToWaitGroup"
	GrackleApi_CompleteJobsFromWaitGroup_FullMethodName  = "/com.evrblk.grackle.v1beta.GrackleApi/CompleteJobsFromWaitGroup"
	GrackleApi_ListWaitGroupCompletedJobs_FullMethodName = "/com.evrblk.grackle.v1beta.GrackleApi/ListWaitGroupCompletedJobs"
	GrackleApi_WaitForWaitGroup_FullMethodName           = "/com.evrblk.grackle.v1beta.GrackleApi/WaitForWaitGroup"
	GrackleApi_AcquireLock_FullMethodName                = "/com.evrblk.grackle.v1beta.GrackleApi/AcquireLock"
	GrackleApi_ReleaseLock_FullMethodName                = "/com.evrblk.grackle.v1beta.GrackleApi/ReleaseLock"
	GrackleApi_GetLock_FullMethodName                    = "/com.evrblk.grackle.v1beta.GrackleApi/GetLock"
	GrackleApi_DeleteLock_FullMethodName                 = "/com.evrblk.grackle.v1beta.GrackleApi/DeleteLock"
	GrackleApi_ListLocks_FullMethodName                  = "/com.evrblk.grackle.v1beta.GrackleApi/ListLocks"
	GrackleApi_CreateLockLease_FullMethodName            = "/com.evrblk.grackle.v1beta.GrackleApi/CreateLockLease"
	GrackleApi_RevokeLockLease_FullMethodName            = "/com.evrblk.grackle.v1beta.GrackleApi/RevokeLockLease"
	GrackleApi_RefreshLockLease_FullMethodName           = "/com.evrblk.grackle.v1beta.GrackleApi/RefreshLockLease"
	GrackleApi_ListLockLeases_FullMethodName             = "/com.evrblk.grackle.v1beta.GrackleApi/ListLockLeases"
	GrackleApi_GetLockLease_FullMethodName               = "/com.evrblk.grackle.v1beta.GrackleApi/GetLockLease"
	GrackleApi_CreateBarrier_FullMethodName              = "/com.evrblk.grackle.v1beta.GrackleApi/CreateBarrier"
	GrackleApi_ListBarriers_FullMethodName               = "/com.evrblk.grackle.v1beta.GrackleApi/ListBarriers"
	GrackleApi_GetBarrier_FullMethodName                 = "/com.evrblk.grackle.v1beta.GrackleApi/GetBarrier"
	GrackleApi_DeleteBarrier_FullMethodName              = "/com.evrblk.grackle.v1beta.GrackleApi/DeleteBarrier"
	GrackleApi_UpdateBarrier_FullMethodName              = "/com.evrblk.grackle.v1beta.GrackleApi/UpdateBarrier"
	GrackleApi_ArriveAtBarrier_FullMethodName            = "/com.evrblk.grackle.v1beta.GrackleApi/ArriveAtBarrier"
	GrackleApi_WaitAtBarrier_FullMethodName              = "/com.evrblk.grackle.v1beta.GrackleApi/WaitAtBarrier"
	GrackleApi_ListBarrierParticipants_FullMethodName    = "/com.evrblk.grackle.v1beta.GrackleApi/ListBarrierParticipants"
)

// GrackleApiClient is the client API for GrackleApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrackleApiClient interface {
	CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error)
	ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error)
	GetNamespace(ctx context.Context, in *GetNamespaceRequest, opts ...grpc.CallOption) (*GetNamespaceResponse, error)
	DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*DeleteNamespaceResponse, error)
	UpdateNamespace(ctx context.Context, in *UpdateNamespaceRequest, opts ...grpc.CallOption) (*UpdateNamespaceResponse, error)
	CreateSemaphore(ctx context.Context, in *CreateSemaphoreRequest, opts ...grpc.CallOption) (*CreateSemaphoreResponse, error)
	ListSemaphores(ctx context.Context, in *ListSemaphoresRequest, opts ...grpc.CallOption) (*ListSemaphoresResponse, error)
	GetSemaphore(ctx context.Context, in *GetSemaphoreRequest, opts ...grpc.CallOption) (*GetSemaphoreResponse, error)
	AcquireSemaphore(ctx context.Context, in *AcquireSemaphoreRequest, opts ...grpc.CallOption) (*AcquireSemaphoreResponse, error)
	ReleaseSemaphore(ctx context.Context, in *ReleaseSemaphoreRequest, opts ...grpc.CallOption) (*ReleaseSemaphoreResponse, error)
	UpdateSemaphore(ctx context.Context, in *UpdateSemaphoreRequest, opts ...grpc.CallOption) (*UpdateSemaphoreResponse, error)
	DeleteSemaphore(ctx context.Context, in *DeleteSemaphoreRequest, opts ...grpc.CallOption) (*DeleteSemaphoreResponse, error)
	ListSemaphoreHolders(ctx context.Context, in *ListSemaphoreHoldersRequest, opts ...grpc.CallOption) (*ListSemaphoreHoldersResponse, error)
	CreateSemaphoreLease(ctx context.Context, in *CreateSemaphoreLeaseRequest, opts ...grpc.CallOption) (*CreateSemaphoreLeaseResponse, error)
	RevokeSemaphoreLease(ctx context.Context, in *RevokeSemaphoreLeaseRequest, opts ...grpc.CallOption) (*RevokeSemaphoreLeaseResponse, error)
	RefreshSemaphoreLease(ctx context.Context, in *RefreshSemaphoreLeaseRequest, opts ...grpc.CallOption) (*RefreshSemaphoreLeaseResponse, error)
	ListSemaphoreLeases(ctx context.Context, in *ListSemaphoreLeasesRequest, opts ...grpc.CallOption) (*ListSemaphoreLeasesResponse, error)
	GetSemaphoreLease(ctx context.Context, in *GetSemaphoreLeaseRequest, opts ...grpc.CallOption) (*GetSemaphoreLeaseResponse, error)
	CreateWaitGroup(ctx context.Context, in *CreateWaitGroupRequest, opts ...grpc.CallOption) (*CreateWaitGroupResponse, error)
	UpdateWaitGroup(ctx context.Context, in *UpdateWaitGroupRequest, opts ...grpc.CallOption) (*UpdateWaitGroupResponse, error)
	ListWaitGroups(ctx context.Context, in *ListWaitGroupsRequest, opts ...grpc.CallOption) (*ListWaitGroupsResponse, error)
	GetWaitGroup(ctx context.Context, in *GetWaitGroupRequest, opts ...grpc.CallOption) (*GetWaitGroupResponse, error)
	DeleteWaitGroup(ctx context.Context, in *DeleteWaitGroupRequest, opts ...grpc.CallOption) (*DeleteWaitGroupResponse, error)
	AddJobsToWaitGroup(ctx context.Context, in *AddJobsToWaitGroupRequest, opts ...grpc.CallOption) (*AddJobsToWaitGroupResponse, error)
	CompleteJobsFromWaitGroup(ctx context.Context, in *CompleteJobsFromWaitGroupRequest, opts ...grpc.CallOption) (*CompleteJobsFromWaitGroupResponse, error)
	ListWaitGroupCompletedJobs(ctx context.Context, in *ListWaitGroupCompletedJobsRequest, opts ...grpc.CallOption) (*ListWaitGroupCompletedJobsResponse, error)
	WaitForWaitGroup(ctx context.Context, in *WaitForWaitGroupRequest, opts ...grpc.CallOption) (*WaitForWaitGroupResponse, error)
	AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error)
	ReleaseLock(ctx context.Context, in *ReleaseLockRequest, opts ...grpc.CallOption) (*ReleaseLockResponse, error)
	GetLock(ctx context.Context, in *GetLockRequest, opts ...grpc.CallOption) (*GetLockResponse, error)
	DeleteLock(ctx context.Context, in *DeleteLockRequest, opts ...grpc.CallOption) (*DeleteLockResponse, error)
	ListLocks(ctx context.Context, in *ListLocksRequest, opts ...grpc.CallOption) (*ListLocksResponse, error)
	CreateLockLease(ctx context.Context, in *CreateLockLeaseRequest, opts ...grpc.CallOption) (*CreateLockLeaseResponse, error)
	RevokeLockLease(ctx context.Context, in *RevokeLockLeaseRequest, opts ...grpc.CallOption) (*RevokeLockLeaseResponse, error)
	RefreshLockLease(ctx context.Context, in *RefreshLockLeaseRequest, opts ...grpc.CallOption) (*RefreshLockLeaseResponse, error)
	ListLockLeases(ctx context.Context, in *ListLockLeasesRequest, opts ...grpc.CallOption) (*ListLockLeasesResponse, error)
	GetLockLease(ctx context.Context, in *GetLockLeaseRequest, opts ...grpc.CallOption) (*GetLockLeaseResponse, error)
	CreateBarrier(ctx context.Context, in *CreateBarrierRequest, opts ...grpc.CallOption) (*CreateBarrierResponse, error)
	ListBarriers(ctx context.Context, in *ListBarriersRequest, opts ...grpc.CallOption) (*ListBarriersResponse, error)
	GetBarrier(ctx context.Context, in *GetBarrierRequest, opts ...grpc.CallOption) (*GetBarrierResponse, error)
	DeleteBarrier(ctx context.Context, in *DeleteBarrierRequest, opts ...grpc.CallOption) (*DeleteBarrierResponse, error)
	UpdateBarrier(ctx context.Context, in *UpdateBarrierRequest, opts ...grpc.CallOption) (*UpdateBarrierResponse, error)
	ArriveAtBarrier(ctx context.Context, in *ArriveAtBarrierRequest, opts ...grpc.CallOption) (*ArriveAtBarrierResponse, error)
	WaitAtBarrier(ctx context.Context, in *WaitAtBarrierRequest, opts ...grpc.CallOption) (*WaitAtBarrierResponse, error)
	ListBarrierParticipants(ctx context.Context, in *ListBarrierParticipantsRequest, opts ...grpc.CallOption) (*ListBarrierParticipantsResponse, error)
}

type grackleApiClient struct {
	cc grpc.ClientConnInterface
}

func NewGrackleApiClient(cc grpc.ClientConnInterface) GrackleApiClient {
	return &grackleApiClient{cc}
}

func (c *grackleApiClient) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNamespaceResponse)
	err := c.cc.Invoke(ctx, GrackleApi_CreateNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNamespacesResponse)
	err := c.cc.Invoke(ctx, GrackleApi_ListNamespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) GetNamespace(ctx context.Context, in *GetNamespaceRequest, opts ...grpc.CallOption) (*GetNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNamespaceResponse)
	err := c.cc.Invoke(ctx, GrackleApi_GetNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*DeleteNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNamespaceResponse)
	err := c.cc.Invoke(ctx, GrackleApi_DeleteNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) UpdateNamespace(ctx context.Context, in *UpdateNamespaceRequest, opts ...grpc.CallOption) (*UpdateNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNamespaceResponse)
	err := c.cc.Invoke(ctx, GrackleApi_UpdateNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) CreateSemaphore(ctx context.Context, in *CreateSemaphoreRequest, opts ...grpc.CallOption) (*CreateSemaphoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSemaphoreResponse)
	err := c.cc.Invoke(ctx, GrackleApi_CreateSemaphore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) ListSemaphores(ctx context.Context, in *ListSemaphoresRequest, opts ...grpc.CallOption) (*ListSemaphoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSemaphoresResponse)
	err := c.cc.Invoke(ctx, GrackleApi_ListSemaphores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) GetSemaphore(ctx context.Context, in *GetSemaphoreRequest, opts ...grpc.CallOption) (*GetSemaphoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSemaphoreResponse)
	err := c.cc.Invoke(ctx, GrackleApi_GetSemaphore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) AcquireSemaphore(ctx context.Context, in *AcquireSemaphoreRequest, opts ...grpc.CallOption) (*AcquireSemaphoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireSemaphoreResponse)
	err := c.cc.Invoke(ctx, GrackleApi_AcquireSemaphore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) ReleaseSemaphore(ctx context.Context, in *ReleaseSemaphoreRequest, opts ...grpc.CallOption) (*ReleaseSemaphoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSemaphoreResponse)
	err := c.cc.Invoke(ctx, GrackleApi_ReleaseSemaphore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) UpdateSemaphore(ctx context.Context, in *UpdateSemaphoreRequest, opts ...grpc.CallOption) (*UpdateSemaphoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSemaphoreResponse)
	err := c.cc.Invoke(ctx, GrackleApi_UpdateSemaphore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) DeleteSemaphore(ctx context.Context, in *DeleteSemaphoreRequest, opts ...grpc.CallOption) (*DeleteSemaphoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSemaphoreResponse)
	err := c.cc.Invoke(ctx, GrackleApi_DeleteSemaphore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) ListSemaphoreHolders(ctx context.Context, in *ListSemaphoreHoldersRequest, opts ...grpc.CallOption) (*ListSemaphoreHoldersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSemaphoreHoldersResponse)
	err := c.cc.Invoke(ctx, GrackleApi_ListSemaphoreHolders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) CreateSemaphoreLease(ctx context.Context, in *CreateSemaphoreLeaseRequest, opts ...grpc.CallOption) (*CreateSemaphoreLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSemaphoreLeaseResponse)
	err := c.cc.Invoke(ctx, GrackleApi_CreateSemaphoreLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) RevokeSemaphoreLease(ctx context.Context, in *RevokeSemaphoreLeaseRequest, opts ...grpc.CallOption) (*RevokeSemaphoreLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeSemaphoreLeaseResponse)
	err := c.cc.Invoke(ctx, GrackleApi_RevokeSemaphoreLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) RefreshSemaphoreLease(ctx context.Context, in *RefreshSemaphoreLeaseRequest, opts ...grpc.CallOption) (*RefreshSemaphoreLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshSemaphoreLeaseResponse)
	err := c.cc.Invoke(ctx, GrackleApi_RefreshSemaphoreLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) ListSemaphoreLeases(ctx context.Context, in *ListSemaphoreLeasesRequest, opts ...grpc.CallOption) (*ListSemaphoreLeasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSemaphoreLeasesResponse)
	err := c.cc.Invoke(ctx, GrackleApi_ListSemaphoreLeases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) GetSemaphoreLease(ctx context.Context, in *GetSemaphoreLeaseRequest, opts ...grpc.CallOption) (*GetSemaphoreLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSemaphoreLeaseResponse)
	err := c.cc.Invoke(ctx, GrackleApi_GetSemaphoreLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) CreateWaitGroup(ctx context.Context, in *CreateWaitGroupRequest, opts ...grpc.CallOption) (*CreateWaitGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWaitGroupResponse)
	err := c.cc.Invoke(ctx, GrackleApi_CreateWaitGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) UpdateWaitGroup(ctx context.Context, in *UpdateWaitGroupRequest, opts ...grpc.CallOption) (*UpdateWaitGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWaitGroupResponse)
	err := c.cc.Invoke(ctx, GrackleApi_UpdateWaitGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) ListWaitGroups(ctx context.Context, in *ListWaitGroupsRequest, opts ...grpc.CallOption) (*ListWaitGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWaitGroupsResponse)
	err := c.cc.Invoke(ctx, GrackleApi_ListWaitGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) GetWaitGroup(ctx context.Context, in *GetWaitGroupRequest, opts ...grpc.CallOption) (*GetWaitGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWaitGroupResponse)
	err := c.cc.Invoke(ctx, GrackleApi_GetWaitGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) DeleteWaitGroup(ctx context.Context, in *DeleteWaitGroupRequest, opts ...grpc.CallOption) (*DeleteWaitGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWaitGroupResponse)
	err := c.cc.Invoke(ctx, GrackleApi_DeleteWaitGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) AddJobsToWaitGroup(ctx context.Context, in *AddJobsToWaitGroupRequest, opts ...grpc.CallOption) (*AddJobsToWaitGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddJobsToWaitGroupResponse)
	err := c.cc.Invoke(ctx, GrackleApi_AddJobsToWaitGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) CompleteJobsFromWaitGroup(ctx context.Context, in *CompleteJobsFromWaitGroupRequest, opts ...grpc.CallOption) (*CompleteJobsFromWaitGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteJobsFromWaitGroupResponse)
	err := c.cc.Invoke(ctx, GrackleApi_CompleteJobsFromWaitGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) ListWaitGroupCompletedJobs(ctx context.Context, in *ListWaitGroupCompletedJobsRequest, opts ...grpc.CallOption) (*ListWaitGroupCompletedJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWaitGroupCompletedJobsResponse)
	err := c.cc.Invoke(ctx, GrackleApi_ListWaitGroupCompletedJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) WaitForWaitGroup(ctx context.Context, in *WaitForWaitGroupRequest, opts ...grpc.CallOption) (*WaitForWaitGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitForWaitGroupResponse)
	err := c.cc.Invoke(ctx, GrackleApi_WaitForWaitGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireLockResponse)
	err := c.cc.Invoke(ctx, GrackleApi_AcquireLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) ReleaseLock(ctx context.Context, in *ReleaseLockRequest, opts ...grpc.CallOption) (*ReleaseLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseLockResponse)
	err := c.cc.Invoke(ctx, GrackleApi_ReleaseLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) GetLock(ctx context.Context, in *GetLockRequest, opts ...grpc.CallOption) (*GetLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLockResponse)
	err := c.cc.Invoke(ctx, GrackleApi_GetLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) DeleteLock(ctx context.Context, in *DeleteLockRequest, opts ...grpc.CallOption) (*DeleteLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLockResponse)
	err := c.cc.Invoke(ctx, GrackleApi_DeleteLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) ListLocks(ctx context.Context, in *ListLocksRequest, opts ...grpc.CallOption) (*ListLocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLocksResponse)
	err := c.cc.Invoke(ctx, GrackleApi_ListLocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) CreateLockLease(ctx context.Context, in *CreateLockLeaseRequest, opts ...grpc.CallOption) (*CreateLockLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLockLeaseResponse)
	err := c.cc.Invoke(ctx, GrackleApi_CreateLockLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) RevokeLockLease(ctx context.Context, in *RevokeLockLeaseRequest, opts ...grpc.CallOption) (*RevokeLockLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeLockLeaseResponse)
	err := c.cc.Invoke(ctx, GrackleApi_RevokeLockLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) RefreshLockLease(ctx context.Context, in *RefreshLockLeaseRequest, opts ...grpc.CallOption) (*RefreshLockLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshLockLeaseResponse)
	err := c.cc.Invoke(ctx, GrackleApi_RefreshLockLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) ListLockLeases(ctx context.Context, in *ListLockLeasesRequest, opts ...grpc.CallOption) (*ListLockLeasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLockLeasesResponse)
	err := c.cc.Invoke(ctx, GrackleApi_ListLockLeases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) GetLockLease(ctx context.Context, in *GetLockLeaseRequest, opts ...grpc.CallOption) (*GetLockLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLockLeaseResponse)
	err := c.cc.Invoke(ctx, GrackleApi_GetLockLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) CreateBarrier(ctx context.Context, in *CreateBarrierRequest, opts ...grpc.CallOption) (*CreateBarrierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBarrierResponse)
	err := c.cc.Invoke(ctx, GrackleApi_CreateBarrier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) ListBarriers(ctx context.Context, in *ListBarriersRequest, opts ...grpc.CallOption) (*ListBarriersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBarriersResponse)
	err := c.cc.Invoke(ctx, GrackleApi_ListBarriers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) GetBarrier(ctx context.Context, in *GetBarrierRequest, opts ...grpc.CallOption) (*GetBarrierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBarrierResponse)
	err := c.cc.Invoke(ctx, GrackleApi_GetBarrier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) DeleteBarrier(ctx context.Context, in *DeleteBarrierRequest, opts ...grpc.CallOption) (*DeleteBarrierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBarrierResponse)
	err := c.cc.Invoke(ctx, GrackleApi_DeleteBarrier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) UpdateBarrier(ctx context.Context, in *UpdateBarrierRequest, opts ...grpc.CallOption) (*UpdateBarrierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBarrierResponse)
	err := c.cc.Invoke(ctx, GrackleApi_UpdateBarrier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) ArriveAtBarrier(ctx context.Context, in *ArriveAtBarrierRequest, opts ...grpc.CallOption) (*ArriveAtBarrierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArriveAtBarrierResponse)
	err := c.cc.Invoke(ctx, GrackleApi_ArriveAtBarrier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) WaitAtBarrier(ctx context.Context, in *WaitAtBarrierRequest, opts ...grpc.CallOption) (*WaitAtBarrierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitAtBarrierResponse)
	err := c.cc.Invoke(ctx, GrackleApi_WaitAtBarrier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grackleApiClient) ListBarrierParticipants(ctx context.Context, in *ListBarrierParticipantsRequest, opts ...grpc.CallOption) (*ListBarrierParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBarrierParticipantsResponse)
	err := c.cc.Invoke(ctx, GrackleApi_ListBarrierParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrackleApiServer is the server API for GrackleApi service.
// All implementations must embed UnimplementedGrackleApiServer
// for forward compatibility.
type GrackleApiServer interface {
	CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error)
	ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error)
	GetNamespace(context.Context, *GetNamespaceRequest) (*GetNamespaceResponse, error)
	DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*DeleteNamespaceResponse, error)
	UpdateNamespace(context.Context, *UpdateNamespaceRequest) (*UpdateNamespaceResponse, error)
	CreateSemaphore(context.Context, *CreateSemaphoreRequest) (*CreateSemaphoreResponse, error)
	ListSemaphores(context.Context, *ListSemaphoresRequest) (*ListSemaphoresResponse, error)
	GetSemaphore(context.Context, *GetSemaphoreRequest) (*GetSemaphoreResponse, error)
	AcquireSemaphore(context.Context, *AcquireSemaphoreRequest) (*AcquireSemaphoreResponse, error)
	ReleaseSemaphore(context.Context, *ReleaseSemaphoreRequest) (*ReleaseSemaphoreResponse, error)
	UpdateSemaphore(context.Context, *UpdateSemaphoreRequest) (*UpdateSemaphoreResponse, error)
	DeleteSemaphore(context.Context, *DeleteSemaphoreRequest) (*DeleteSemaphoreResponse, error)
	ListSemaphoreHolders(context.Context, *ListSemaphoreHoldersRequest) (*ListSemaphoreHoldersResponse, error)
	CreateSemaphoreLease(context.Context, *CreateSemaphoreLeaseRequest) (*CreateSemaphoreLeaseResponse, error)
	RevokeSemaphoreLease(context.Context, *RevokeSemaphoreLeaseRequest) (*RevokeSemaphoreLeaseResponse, error)
	RefreshSemaphoreLease(context.Context, *RefreshSemaphoreLeaseRequest) (*RefreshSemaphoreLeaseResponse, error)
	ListSemaphoreLeases(context.Context, *ListSemaphoreLeasesRequest) (*ListSemaphoreLeasesResponse, error)
	GetSemaphoreLease(context.Context, *GetSemaphoreLeaseRequest) (*GetSemaphoreLeaseResponse, error)
	CreateWaitGroup(context.Context, *CreateWaitGroupRequest) (*CreateWaitGroupResponse, error)
	UpdateWaitGroup(context.Context, *UpdateWaitGroupRequest) (*UpdateWaitGroupResponse, error)
	ListWaitGroups(context.Context, *ListWaitGroupsRequest) (*ListWaitGroupsResponse, error)
	GetWaitGroup(context.Context, *GetWaitGroupRequest) (*GetWaitGroupResponse, error)
	DeleteWaitGroup(context.Context, *DeleteWaitGroupRequest) (*DeleteWaitGroupResponse, error)
	AddJobsToWaitGroup(context.Context, *AddJobsToWaitGroupRequest) (*AddJobsToWaitGroupResponse, error)
	CompleteJobsFromWaitGroup(context.Context, *CompleteJobsFromWaitGroupRequest) (*CompleteJobsFromWaitGroupResponse, error)
	ListWaitGroupCompletedJobs(context.Context, *ListWaitGroupCompletedJobsRequest) (*ListWaitGroupCompletedJobsResponse, error)
	WaitForWaitGroup(context.Context, *WaitForWaitGroupRequest) (*WaitForWaitGroupResponse, error)
	AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error)
	ReleaseLock(context.Context, *ReleaseLockRequest) (*ReleaseLockResponse, error)
	GetLock(context.Context, *GetLockRequest) (*GetLockResponse, error)
	DeleteLock(context.Context, *DeleteLockRequest) (*DeleteLockResponse, error)
	ListLocks(context.Context, *ListLocksRequest) (*ListLocksResponse, error)
	CreateLockLease(context.Context, *CreateLockLeaseRequest) (*CreateLockLeaseResponse, error)
	RevokeLockLease(context.Context, *RevokeLockLeaseRequest) (*RevokeLockLeaseResponse, error)
	RefreshLockLease(context.Context, *RefreshLockLeaseRequest) (*RefreshLockLeaseResponse, error)
	ListLockLeases(context.Context, *ListLockLeasesRequest) (*ListLockLeasesResponse, error)
	GetLockLease(context.Context, *GetLockLeaseRequest) (*GetLockLeaseResponse, error)
	CreateBarrier(context.Context, *CreateBarrierRequest) (*CreateBarrierResponse, error)
	ListBarriers(context.Context, *ListBarriersRequest) (*ListBarriersResponse, error)
	GetBarrier(context.Context, *GetBarrierRequest) (*GetBarrierResponse, error)
	DeleteBarrier(context.Context, *DeleteBarrierRequest) (*DeleteBarrierResponse, error)
	UpdateBarrier(context.Context, *UpdateBarrierRequest) (*UpdateBarrierResponse, error)
	ArriveAtBarrier(context.Context, *ArriveAtBarrierRequest) (*ArriveAtBarrierResponse, error)
	WaitAtBarrier(context.Context, *WaitAtBarrierRequest) (*WaitAtBarrierResponse, error)
	ListBarrierParticipants(context.Context, *ListBarrierParticipantsRequest) (*ListBarrierParticipantsResponse, error)
	mustEmbedUnimplementedGrackleApiServer()
}

// UnimplementedGrackleApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrackleApiServer struct{}

func (UnimplementedGrackleApiServer) CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNamespace not implemented")
}
func (UnimplementedGrackleApiServer) ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (UnimplementedGrackleApiServer) GetNamespace(context.Context, *GetNamespaceRequest) (*GetNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNamespace not implemented")
}
func (UnimplementedGrackleApiServer) DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*DeleteNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNamespace not implemented")
}
func (UnimplementedGrackleApiServer) UpdateNamespace(context.Context, *UpdateNamespaceRequest) (*UpdateNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNamespace not implemented")
}
func (UnimplementedGrackleApiServer) CreateSemaphore(context.Context, *CreateSemaphoreRequest) (*CreateSemaphoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSemaphore not implemented")
}
func (UnimplementedGrackleApiServer) ListSemaphores(context.Context, *ListSemaphoresRequest) (*ListSemaphoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSemaphores not implemented")
}
func (UnimplementedGrackleApiServer) GetSemaphore(context.Context, *GetSemaphoreRequest) (*GetSemaphoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSemaphore not implemented")
}
func (UnimplementedGrackleApiServer) AcquireSemaphore(context.Context, *AcquireSemaphoreRequest) (*AcquireSemaphoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireSemaphore not implemented")
}
func (UnimplementedGrackleApiServer) ReleaseSemaphore(context.Context, *ReleaseSemaphoreRequest) (*ReleaseSemaphoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseSemaphore not implemented")
}
func (UnimplementedGrackleApiServer) UpdateSemaphore(context.Context, *UpdateSemaphoreRequest) (*UpdateSemaphoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSemaphore not implemented")
}
func (UnimplementedGrackleApiServer) DeleteSemaphore(context.Context, *DeleteSemaphoreRequest) (*DeleteSemaphoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSemaphore not implemented")
}
func (UnimplementedGrackleApiServer) ListSemaphoreHolders(context.Context, *ListSemaphoreHoldersRequest) (*ListSemaphoreHoldersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSemaphoreHolders not implemented")
}
func (UnimplementedGrackleApiServer) CreateSemaphoreLease(context.Context, *CreateSemaphoreLeaseRequest) (*CreateSemaphoreLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSemaphoreLease not implemented")
}
func (UnimplementedGrackleApiServer) RevokeSemaphoreLease(context.Context, *RevokeSemaphoreLeaseRequest) (*RevokeSemaphoreLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeSemaphoreLease not implemented")
}
func (UnimplementedGrackleApiServer) RefreshSemaphoreLease(context.Context, *RefreshSemaphoreLeaseRequest) (*RefreshSemaphoreLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshSemaphoreLease not implemented")
}
func (UnimplementedGrackleApiServer) ListSemaphoreLeases(context.Context, *ListSemaphoreLeasesRequest) (*ListSemaphoreLeasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSemaphoreLeases not implemented")
}
func (UnimplementedGrackleApiServer) GetSemaphoreLease(context.Context, *GetSemaphoreLeaseRequest) (*GetSemaphoreLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSemaphoreLease not implemented")
}
func (UnimplementedGrackleApiServer) CreateWaitGroup(context.Context, *CreateWaitGroupRequest) (*CreateWaitGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWaitGroup not implemented")
}
func (UnimplementedGrackleApiServer) UpdateWaitGroup(context.Context, *UpdateWaitGroupRequest) (*UpdateWaitGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWaitGroup not implemented")
}
func (UnimplementedGrackleApiServer) ListWaitGroups(context.Context, *ListWaitGroupsRequest) (*ListWaitGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWaitGroups not implemented")
}
func (UnimplementedGrackleApiServer) GetWaitGroup(context.Context, *GetWaitGroupRequest) (*GetWaitGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWaitGroup not implemented")
}
func (UnimplementedGrackleApiServer) DeleteWaitGroup(context.Context, *DeleteWaitGroupRequest) (*DeleteWaitGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWaitGroup not implemented")
}
func (UnimplementedGrackleApiServer) AddJobsToWaitGroup(context.Context, *AddJobsToWaitGroupRequest) (*AddJobsToWaitGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddJobsToWaitGroup not implemented")
}
func (UnimplementedGrackleApiServer) CompleteJobsFromWaitGroup(context.Context, *CompleteJobsFromWaitGroupRequest) (*CompleteJobsFromWaitGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteJobsFromWaitGroup not implemented")
}
func (UnimplementedGrackleApiServer) ListWaitGroupCompletedJobs(context.Context, *ListWaitGroupCompletedJobsRequest) (*ListWaitGroupCompletedJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWaitGroupCompletedJobs not implemented")
}
func (UnimplementedGrackleApiServer) WaitForWaitGroup(context.Context, *WaitForWaitGroupRequest) (*WaitForWaitGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitForWaitGroup not implemented")
}
func (UnimplementedGrackleApiServer) AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireLock not implemented")
}
func (UnimplementedGrackleApiServer) ReleaseLock(context.Context, *ReleaseLockRequest) (*ReleaseLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseLock not implemented")
}
func (UnimplementedGrackleApiServer) GetLock(context.Context, *GetLockRequest) (*GetLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLock not implemented")
}
func (UnimplementedGrackleApiServer) DeleteLock(context.Context, *DeleteLockRequest) (*DeleteLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLock not implemented")
}
func (UnimplementedGrackleApiServer) ListLocks(context.Context, *ListLocksRequest) (*ListLocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLocks not implemented")
}
func (UnimplementedGrackleApiServer) CreateLockLease(context.Context, *CreateLockLeaseRequest) (*CreateLockLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLockLease not implemented")
}
func (UnimplementedGrackleApiServer) RevokeLockLease(context.Context, *RevokeLockLeaseRequest) (*RevokeLockLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeLockLease not implemented")
}
func (UnimplementedGrackleApiServer) RefreshLockLease(context.Context, *RefreshLockLeaseRequest) (*RefreshLockLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshLockLease not implemented")
}
func (UnimplementedGrackleApiServer) ListLockLeases(context.Context, *ListLockLeasesRequest) (*ListLockLeasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLockLeases not implemented")
}
func (UnimplementedGrackleApiServer) GetLockLease(context.Context, *GetLockLeaseRequest) (*GetLockLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLockLease not implemented")
}
func (UnimplementedGrackleApiServer) CreateBarrier(context.Context, *CreateBarrierRequest) (*CreateBarrierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBarrier not implemented")
}
func (UnimplementedGrackleApiServer) ListBarriers(context.Context, *ListBarriersRequest) (*ListBarriersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBarriers not implemented")
}
func (UnimplementedGrackleApiServer) GetBarrier(context.Context, *GetBarrierRequest) (*GetBarrierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBarrier not implemented")
}
func (UnimplementedGrackleApiServer) DeleteBarrier(context.Context, *DeleteBarrierRequest) (*DeleteBarrierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBarrier not implemented")
}
func (UnimplementedGrackleApiServer) UpdateBarrier(context.Context, *UpdateBarrierRequest) (*UpdateBarrierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBarrier not implemented")
}
func (UnimplementedGrackleApiServer) ArriveAtBarrier(context.Context, *ArriveAtBarrierRequest) (*ArriveAtBarrierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArriveAtBarrier not implemented")
}
func (UnimplementedGrackleApiServer) WaitAtBarrier(context.Context, *WaitAtBarrierRequest) (*WaitAtBarrierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitAtBarrier not implemented")
}
func (UnimplementedGrackleApiServer) ListBarrierParticipants(context.Context, *ListBarrierParticipantsRequest) (*ListBarrierParticipantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBarrierParticipants not implemented")
}
func (UnimplementedGrackleApiServer) mustEmbedUnimplementedGrackleApiServer() {}
func (UnimplementedGrackleApiServer) testEmbeddedByValue()                    {}

// UnsafeGrackleApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrackleApiServer will
// result in compilation errors.
type UnsafeGrackleApiServer interface {
	mustEmbedUnimplementedGrackleApiServer()
}

func RegisterGrackleApiServer(s grpc.ServiceRegistrar, srv GrackleApiServer) {
	// If the following call pancis, it indicates UnimplementedGrackleApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrackleApi_ServiceDesc, srv)
}

func _GrackleApi_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_CreateNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).CreateNamespace(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNamespacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_ListNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).ListNamespaces(ctx, req.(*ListNamespacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_GetNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).GetNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_GetNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).GetNamespace(ctx, req.(*GetNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).DeleteNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_DeleteNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).DeleteNamespace(ctx, req.(*DeleteNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_UpdateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).UpdateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_UpdateNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).UpdateNamespace(ctx, req.(*UpdateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_CreateSemaphore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSemaphoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).CreateSemaphore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_CreateSemaphore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).CreateSemaphore(ctx, req.(*CreateSemaphoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_ListSemaphores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSemaphoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).ListSemaphores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_ListSemaphores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).ListSemaphores(ctx, req.(*ListSemaphoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_GetSemaphore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSemaphoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).GetSemaphore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_GetSemaphore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).GetSemaphore(ctx, req.(*GetSemaphoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_AcquireSemaphore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireSemaphoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).AcquireSemaphore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_AcquireSemaphore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).AcquireSemaphore(ctx, req.(*AcquireSemaphoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_ReleaseSemaphore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSemaphoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).ReleaseSemaphore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_ReleaseSemaphore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).ReleaseSemaphore(ctx, req.(*ReleaseSemaphoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_UpdateSemaphore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSemaphoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).UpdateSemaphore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_UpdateSemaphore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).UpdateSemaphore(ctx, req.(*UpdateSemaphoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_DeleteSemaphore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSemaphoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).DeleteSemaphore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_DeleteSemaphore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).DeleteSemaphore(ctx, req.(*DeleteSemaphoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_ListSemaphoreHolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSemaphoreHoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).ListSemaphoreHolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_ListSemaphoreHolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).ListSemaphoreHolders(ctx, req.(*ListSemaphoreHoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_CreateSemaphoreLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSemaphoreLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).CreateSemaphoreLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_CreateSemaphoreLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).CreateSemaphoreLease(ctx, req.(*CreateSemaphoreLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_RevokeSemaphoreLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeSemaphoreLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).RevokeSemaphoreLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_RevokeSemaphoreLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).RevokeSemaphoreLease(ctx, req.(*RevokeSemaphoreLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_RefreshSemaphoreLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshSemaphoreLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).RefreshSemaphoreLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_RefreshSemaphoreLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).RefreshSemaphoreLease(ctx, req.(*RefreshSemaphoreLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_ListSemaphoreLeases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSemaphoreLeasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).ListSemaphoreLeases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_ListSemaphoreLeases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).ListSemaphoreLeases(ctx, req.(*ListSemaphoreLeasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_GetSemaphoreLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSemaphoreLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).GetSemaphoreLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_GetSemaphoreLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).GetSemaphoreLease(ctx, req.(*GetSemaphoreLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_CreateWaitGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWaitGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).CreateWaitGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_CreateWaitGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).CreateWaitGroup(ctx, req.(*CreateWaitGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_UpdateWaitGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWaitGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).UpdateWaitGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_UpdateWaitGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).UpdateWaitGroup(ctx, req.(*UpdateWaitGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_ListWaitGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWaitGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).ListWaitGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_ListWaitGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).ListWaitGroups(ctx, req.(*ListWaitGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_GetWaitGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWaitGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).GetWaitGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_GetWaitGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).GetWaitGroup(ctx, req.(*GetWaitGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_DeleteWaitGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWaitGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).DeleteWaitGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_DeleteWaitGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).DeleteWaitGroup(ctx, req.(*DeleteWaitGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_AddJobsToWaitGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddJobsToWaitGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).AddJobsToWaitGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_AddJobsToWaitGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).AddJobsToWaitGroup(ctx, req.(*AddJobsToWaitGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_CompleteJobsFromWaitGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteJobsFromWaitGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).CompleteJobsFromWaitGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_CompleteJobsFromWaitGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).CompleteJobsFromWaitGroup(ctx, req.(*CompleteJobsFromWaitGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_ListWaitGroupCompletedJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWaitGroupCompletedJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).ListWaitGroupCompletedJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_ListWaitGroupCompletedJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).ListWaitGroupCompletedJobs(ctx, req.(*ListWaitGroupCompletedJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_WaitForWaitGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitForWaitGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).WaitForWaitGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_WaitForWaitGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).WaitForWaitGroup(ctx, req.(*WaitForWaitGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_AcquireLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).AcquireLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_AcquireLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).AcquireLock(ctx, req.(*AcquireLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_ReleaseLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).ReleaseLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_ReleaseLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).ReleaseLock(ctx, req.(*ReleaseLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_GetLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).GetLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_GetLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).GetLock(ctx, req.(*GetLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_DeleteLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).DeleteLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_DeleteLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).DeleteLock(ctx, req.(*DeleteLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_ListLocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).ListLocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_ListLocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).ListLocks(ctx, req.(*ListLocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_CreateLockLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLockLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).CreateLockLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_CreateLockLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).CreateLockLease(ctx, req.(*CreateLockLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_RevokeLockLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeLockLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).RevokeLockLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_RevokeLockLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).RevokeLockLease(ctx, req.(*RevokeLockLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_RefreshLockLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshLockLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).RefreshLockLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_RefreshLockLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).RefreshLockLease(ctx, req.(*RefreshLockLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_ListLockLeases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLockLeasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).ListLockLeases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_ListLockLeases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).ListLockLeases(ctx, req.(*ListLockLeasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_GetLockLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLockLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).GetLockLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_GetLockLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).GetLockLease(ctx, req.(*GetLockLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_CreateBarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBarrierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).CreateBarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_CreateBarrier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).CreateBarrier(ctx, req.(*CreateBarrierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_ListBarriers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBarriersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).ListBarriers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_ListBarriers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).ListBarriers(ctx, req.(*ListBarriersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_GetBarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBarrierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).GetBarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_GetBarrier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).GetBarrier(ctx, req.(*GetBarrierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_DeleteBarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBarrierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).DeleteBarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_DeleteBarrier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).DeleteBarrier(ctx, req.(*DeleteBarrierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_UpdateBarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBarrierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).UpdateBarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_UpdateBarrier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).UpdateBarrier(ctx, req.(*UpdateBarrierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_ArriveAtBarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArriveAtBarrierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).ArriveAtBarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_ArriveAtBarrier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).ArriveAtBarrier(ctx, req.(*ArriveAtBarrierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_WaitAtBarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitAtBarrierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).WaitAtBarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_WaitAtBarrier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).WaitAtBarrier(ctx, req.(*WaitAtBarrierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrackleApi_ListBarrierParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBarrierParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrackleApiServer).ListBarrierParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrackleApi_ListBarrierParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrackleApiServer).ListBarrierParticipants(ctx, req.(*ListBarrierParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrackleApi_ServiceDesc is the grpc.ServiceDesc for GrackleApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrackleApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.evrblk.grackle.v1beta.GrackleApi",
	HandlerType: (*GrackleApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNamespace",
			Handler:    _GrackleApi_CreateNamespace_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _GrackleApi_ListNamespaces_Handler,
		},
		{
			MethodName: "GetNamespace",
			Handler:    _GrackleApi_GetNamespace_Handler,
		},
		{
			MethodName: "DeleteNamespace",
			Handler:    _GrackleApi_DeleteNamespace_Handler,
		},
		{
			MethodName: "UpdateNamespace",
			Handler:    _GrackleApi_UpdateNamespace_Handler,
		},
		{
			MethodName: "CreateSemaphore",
			Handler:    _GrackleApi_CreateSemaphore_Handler,
		},
		{
			MethodName: "ListSemaphores",
			Handler:    _GrackleApi_ListSemaphores_Handler,
		},
		{
			MethodName: "GetSemaphore",
			Handler:    _GrackleApi_GetSemaphore_Handler,
		},
		{
			MethodName: "AcquireSemaphore",
			Handler:    _GrackleApi_AcquireSemaphore_Handler,
		},
		{
			MethodName: "ReleaseSemaphore",
			Handler:    _GrackleApi_ReleaseSemaphore_Handler,
		},
		{
			MethodName: "UpdateSemaphore",
			Handler:    _GrackleApi_UpdateSemaphore_Handler,
		},
		{
			MethodName: "DeleteSemaphore",
			Handler:    _GrackleApi_DeleteSemaphore_Handler,
		},
		{
			MethodName: "ListSemaphoreHolders",
			Handler:    _GrackleApi_ListSemaphoreHolders_Handler,
		},
		{
			MethodName: "CreateSemaphoreLease",
			Handler:    _GrackleApi_CreateSemaphoreLease_Handler,
		},
		{
			MethodName: "RevokeSemaphoreLease",
			Handler:    _GrackleApi_RevokeSemaphoreLease_Handler,
		},
		{
			MethodName: "RefreshSemaphoreLease",
			Handler:    _GrackleApi_RefreshSemaphoreLease_Handler,
		},
		{
			MethodName: "ListSemaphoreLeases",
			Handler:    _GrackleApi_ListSemaphoreLeases_Handler,
		},
		{
			MethodName: "GetSemaphoreLease",
			Handler:    _GrackleApi_GetSemaphoreLease_Handler,
		},
		{
			MethodName: "CreateWaitGroup",
			Handler:    _GrackleApi_CreateWaitGroup_Handler,
		},
		{
			MethodName: "UpdateWaitGroup",
			Handler:    _GrackleApi_UpdateWaitGroup_Handler,
		},
		{
			MethodName: "ListWaitGroups",
			Handler:    _GrackleApi_ListWaitGroups_Handler,
		},
		{
			MethodName: "GetWaitGroup",
			Handler:    _GrackleApi_GetWaitGroup_Handler,
		},
		{
			MethodName: "DeleteWaitGroup",
			Handler:    _GrackleApi_DeleteWaitGroup_Handler,
		},
		{
			MethodName: "AddJobsToWaitGroup",
			Handler:    _GrackleApi_AddJobsToWaitGroup_Handler,
		},
		{
			MethodName: "CompleteJobsFromWaitGroup",
			Handler:    _GrackleApi_CompleteJobsFromWaitGroup_Handler,
		},
		{
			MethodName: "ListWaitGroupCompletedJobs",
			Handler:    _GrackleApi_ListWaitGroupCompletedJobs_Handler,
		},
		{
			MethodName: "WaitForWaitGroup",
			Handler:    _GrackleApi_WaitForWaitGroup_Handler,
		},
		{
			MethodName: "AcquireLock",
			Handler:    _GrackleApi_AcquireLock_Handler,
		},
		{
			MethodName: "ReleaseLock",
			Handler:    _GrackleApi_ReleaseLock_Handler,
		},
		{
			MethodName: "GetLock",
			Handler:    _GrackleApi_GetLock_Handler,
		},
		{
			MethodName: "DeleteLock",
			Handler:    _GrackleApi_DeleteLock_Handler,
		},
		{
			MethodName: "ListLocks",
			Handler:    _GrackleApi_ListLocks_Handler,
		},
		{
			MethodName: "CreateLockLease",
			Handler:    _GrackleApi_CreateLockLease_Handler,
		},
		{
			MethodName: "RevokeLockLease",
			Handler:    _GrackleApi_RevokeLockLease_Handler,
		},
		{
			MethodName: "RefreshLockLease",
			Handler:    _GrackleApi_RefreshLockLease_Handler,
		},
		{
			MethodName: "ListLockLeases",
			Handler:    _GrackleApi_ListLockLeases_Handler,
		},
		{
			MethodName: "GetLockLease",
			Handler:    _GrackleApi_GetLockLease_Handler,
		},
		{
			MethodName: "CreateBarrier",
			Handler:    _GrackleApi_CreateBarrier_Handler,
		},
		{
			MethodName: "ListBarriers",
			Handler:    _GrackleApi_ListBarriers_Handler,
		},
		{
			MethodName: "GetBarrier",
			Handler:    _GrackleApi_GetBarrier_Handler,
		},
		{
			MethodName: "DeleteBarrier",
			Handler:    _GrackleApi_DeleteBarrier_Handler,
		},
		{
			MethodName: "UpdateBarrier",
			Handler:    _GrackleApi_UpdateBarrier_Handler,
		},
		{
			MethodName: "ArriveAtBarrier",
			Handler:    _GrackleApi_ArriveAtBarrier_Handler,
		},
		{
			MethodName: "WaitAtBarrier",
			Handler:    _GrackleApi_WaitAtBarrier_Handler,
		},
		{
			MethodName: "ListBarrierParticipants",
			Handler:    _GrackleApi_ListBarrierParticipants_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/grackle/v1beta/api.proto",
}
