// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.0
// source: proto/iam/v0/api.proto

package iam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type GetRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type ListRolesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaginationToken string                 `protobuf:"bytes,1,opt,name=pagination_token,json=paginationToken,proto3" json:"pagination_token,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{6}
}

func (x *ListRolesRequest) GetPaginationToken() string {
	if x != nil {
		return x.PaginationToken
	}
	return ""
}

func (x *ListRolesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRolesResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Roles                   []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	NextPaginationToken     string                 `protobuf:"bytes,2,opt,name=next_pagination_token,json=nextPaginationToken,proto3" json:"next_pagination_token,omitempty"`
	PreviousPaginationToken string                 `protobuf:"bytes,3,opt,name=previous_pagination_token,json=previousPaginationToken,proto3" json:"previous_pagination_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{7}
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRolesResponse) GetNextPaginationToken() string {
	if x != nil {
		return x.NextPaginationToken
	}
	return ""
}

func (x *ListRolesResponse) GetPreviousPaginationToken() string {
	if x != nil {
		return x.PreviousPaginationToken
	}
	return ""
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{9}
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	RoleId        string                 `protobuf:"bytes,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{10}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{11}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ListUsersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaginationToken string                 `protobuf:"bytes,1,opt,name=pagination_token,json=paginationToken,proto3" json:"pagination_token,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{16}
}

func (x *ListUsersRequest) GetPaginationToken() string {
	if x != nil {
		return x.PaginationToken
	}
	return ""
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListUsersResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Users                   []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextPaginationToken     string                 `protobuf:"bytes,2,opt,name=next_pagination_token,json=nextPaginationToken,proto3" json:"next_pagination_token,omitempty"`
	PreviousPaginationToken string                 `protobuf:"bytes,3,opt,name=previous_pagination_token,json=previousPaginationToken,proto3" json:"previous_pagination_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{17}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetNextPaginationToken() string {
	if x != nil {
		return x.NextPaginationToken
	}
	return ""
}

func (x *ListUsersResponse) GetPreviousPaginationToken() string {
	if x != nil {
		return x.PreviousPaginationToken
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{19}
}

type CreateApiKeyRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	RoleId      string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	UserId      string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt   int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Types that are valid to be assigned to KeyType:
	//
	//	*CreateApiKeyRequest_Alfa
	//	*CreateApiKeyRequest_Bravo
	//	*CreateApiKeyRequest_Charlie
	KeyType       isCreateApiKeyRequest_KeyType `protobuf_oneof:"key_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiKeyRequest) Reset() {
	*x = CreateApiKeyRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyRequest) ProtoMessage() {}

func (x *CreateApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{20}
}

func (x *CreateApiKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateApiKeyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateApiKeyRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *CreateApiKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateApiKeyRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *CreateApiKeyRequest) GetKeyType() isCreateApiKeyRequest_KeyType {
	if x != nil {
		return x.KeyType
	}
	return nil
}

func (x *CreateApiKeyRequest) GetAlfa() *CreateAlfaKeyRequest {
	if x != nil {
		if x, ok := x.KeyType.(*CreateApiKeyRequest_Alfa); ok {
			return x.Alfa
		}
	}
	return nil
}

func (x *CreateApiKeyRequest) GetBravo() *CreateBravoKeyRequest {
	if x != nil {
		if x, ok := x.KeyType.(*CreateApiKeyRequest_Bravo); ok {
			return x.Bravo
		}
	}
	return nil
}

func (x *CreateApiKeyRequest) GetCharlie() *CreateCharlieKeyRequest {
	if x != nil {
		if x, ok := x.KeyType.(*CreateApiKeyRequest_Charlie); ok {
			return x.Charlie
		}
	}
	return nil
}

type isCreateApiKeyRequest_KeyType interface {
	isCreateApiKeyRequest_KeyType()
}

type CreateApiKeyRequest_Alfa struct {
	Alfa *CreateAlfaKeyRequest `protobuf:"bytes,6,opt,name=alfa,proto3,oneof"`
}

type CreateApiKeyRequest_Bravo struct {
	Bravo *CreateBravoKeyRequest `protobuf:"bytes,7,opt,name=bravo,proto3,oneof"`
}

type CreateApiKeyRequest_Charlie struct {
	Charlie *CreateCharlieKeyRequest `protobuf:"bytes,8,opt,name=charlie,proto3,oneof"`
}

func (*CreateApiKeyRequest_Alfa) isCreateApiKeyRequest_KeyType() {}

func (*CreateApiKeyRequest_Bravo) isCreateApiKeyRequest_KeyType() {}

func (*CreateApiKeyRequest_Charlie) isCreateApiKeyRequest_KeyType() {}

type CreateAlfaKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicPem     string                 `protobuf:"bytes,1,opt,name=public_pem,json=publicPem,proto3" json:"public_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlfaKeyRequest) Reset() {
	*x = CreateAlfaKeyRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlfaKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlfaKeyRequest) ProtoMessage() {}

func (x *CreateAlfaKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlfaKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAlfaKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{21}
}

func (x *CreateAlfaKeyRequest) GetPublicPem() string {
	if x != nil {
		return x.PublicPem
	}
	return ""
}

type CreateBravoKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBravoKeyRequest) Reset() {
	*x = CreateBravoKeyRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBravoKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBravoKeyRequest) ProtoMessage() {}

func (x *CreateBravoKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBravoKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateBravoKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{22}
}

type CreateCharlieKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharlieKeyRequest) Reset() {
	*x = CreateCharlieKeyRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharlieKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharlieKeyRequest) ProtoMessage() {}

func (x *CreateCharlieKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharlieKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateCharlieKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{23}
}

type CreateApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *NewApiKey             `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiKeyResponse) Reset() {
	*x = CreateApiKeyResponse{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyResponse) ProtoMessage() {}

func (x *CreateApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{24}
}

func (x *CreateApiKeyResponse) GetApiKey() *NewApiKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

type NewApiKey struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt   int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RoleId      string                 `protobuf:"bytes,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	UserId      string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt   int64                  `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Types that are valid to be assigned to KeyType:
	//
	//	*NewApiKey_Alfa
	//	*NewApiKey_Bravo
	//	*NewApiKey_Charlie
	KeyType       isNewApiKey_KeyType `protobuf_oneof:"key_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewApiKey) Reset() {
	*x = NewApiKey{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewApiKey) ProtoMessage() {}

func (x *NewApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewApiKey.ProtoReflect.Descriptor instead.
func (*NewApiKey) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{25}
}

func (x *NewApiKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewApiKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewApiKey) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NewApiKey) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *NewApiKey) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *NewApiKey) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *NewApiKey) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NewApiKey) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *NewApiKey) GetKeyType() isNewApiKey_KeyType {
	if x != nil {
		return x.KeyType
	}
	return nil
}

func (x *NewApiKey) GetAlfa() *NewAlfaKey {
	if x != nil {
		if x, ok := x.KeyType.(*NewApiKey_Alfa); ok {
			return x.Alfa
		}
	}
	return nil
}

func (x *NewApiKey) GetBravo() *NewBravoKey {
	if x != nil {
		if x, ok := x.KeyType.(*NewApiKey_Bravo); ok {
			return x.Bravo
		}
	}
	return nil
}

func (x *NewApiKey) GetCharlie() *NewCharlieKey {
	if x != nil {
		if x, ok := x.KeyType.(*NewApiKey_Charlie); ok {
			return x.Charlie
		}
	}
	return nil
}

type isNewApiKey_KeyType interface {
	isNewApiKey_KeyType()
}

type NewApiKey_Alfa struct {
	Alfa *NewAlfaKey `protobuf:"bytes,9,opt,name=alfa,proto3,oneof"`
}

type NewApiKey_Bravo struct {
	Bravo *NewBravoKey `protobuf:"bytes,10,opt,name=bravo,proto3,oneof"`
}

type NewApiKey_Charlie struct {
	Charlie *NewCharlieKey `protobuf:"bytes,11,opt,name=charlie,proto3,oneof"`
}

func (*NewApiKey_Alfa) isNewApiKey_KeyType() {}

func (*NewApiKey_Bravo) isNewApiKey_KeyType() {}

func (*NewApiKey_Charlie) isNewApiKey_KeyType() {}

type NewAlfaKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicPem     string                 `protobuf:"bytes,1,opt,name=public_pem,json=publicPem,proto3" json:"public_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewAlfaKey) Reset() {
	*x = NewAlfaKey{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAlfaKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAlfaKey) ProtoMessage() {}

func (x *NewAlfaKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAlfaKey.ProtoReflect.Descriptor instead.
func (*NewAlfaKey) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{26}
}

func (x *NewAlfaKey) GetPublicPem() string {
	if x != nil {
		return x.PublicPem
	}
	return ""
}

type NewBravoKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewBravoKey) Reset() {
	*x = NewBravoKey{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewBravoKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBravoKey) ProtoMessage() {}

func (x *NewBravoKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBravoKey.ProtoReflect.Descriptor instead.
func (*NewBravoKey) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{27}
}

func (x *NewBravoKey) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type NewCharlieKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewCharlieKey) Reset() {
	*x = NewCharlieKey{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewCharlieKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCharlieKey) ProtoMessage() {}

func (x *NewCharlieKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCharlieKey.ProtoReflect.Descriptor instead.
func (*NewCharlieKey) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{28}
}

type GetApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeyId      string                 `protobuf:"bytes,1,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiKeyRequest) Reset() {
	*x = GetApiKeyRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiKeyRequest) ProtoMessage() {}

func (x *GetApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiKeyRequest.ProtoReflect.Descriptor instead.
func (*GetApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{29}
}

func (x *GetApiKeyRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

type GetApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *ApiKey                `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiKeyResponse) Reset() {
	*x = GetApiKeyResponse{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiKeyResponse) ProtoMessage() {}

func (x *GetApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiKeyResponse.ProtoReflect.Descriptor instead.
func (*GetApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{30}
}

func (x *GetApiKeyResponse) GetApiKey() *ApiKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

type ListApiKeysRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaginationToken string                 `protobuf:"bytes,1,opt,name=pagination_token,json=paginationToken,proto3" json:"pagination_token,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListApiKeysRequest) Reset() {
	*x = ListApiKeysRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysRequest) ProtoMessage() {}

func (x *ListApiKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiKeysRequest.ProtoReflect.Descriptor instead.
func (*ListApiKeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{31}
}

func (x *ListApiKeysRequest) GetPaginationToken() string {
	if x != nil {
		return x.PaginationToken
	}
	return ""
}

func (x *ListApiKeysRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListApiKeysResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys                 []*ApiKey              `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	NextPaginationToken     string                 `protobuf:"bytes,2,opt,name=next_pagination_token,json=nextPaginationToken,proto3" json:"next_pagination_token,omitempty"`
	PreviousPaginationToken string                 `protobuf:"bytes,3,opt,name=previous_pagination_token,json=previousPaginationToken,proto3" json:"previous_pagination_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListApiKeysResponse) Reset() {
	*x = ListApiKeysResponse{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysResponse) ProtoMessage() {}

func (x *ListApiKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiKeysResponse.ProtoReflect.Descriptor instead.
func (*ListApiKeysResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{32}
}

func (x *ListApiKeysResponse) GetApiKeys() []*ApiKey {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

func (x *ListApiKeysResponse) GetNextPaginationToken() string {
	if x != nil {
		return x.NextPaginationToken
	}
	return ""
}

func (x *ListApiKeysResponse) GetPreviousPaginationToken() string {
	if x != nil {
		return x.PreviousPaginationToken
	}
	return ""
}

type DeleteApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeyId      string                 `protobuf:"bytes,1,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiKeyRequest) Reset() {
	*x = DeleteApiKeyRequest{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiKeyRequest) ProtoMessage() {}

func (x *DeleteApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{33}
}

func (x *DeleteApiKeyRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

type DeleteApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiKeyResponse) Reset() {
	*x = DeleteApiKeyResponse{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiKeyResponse) ProtoMessage() {}

func (x *DeleteApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{34}
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{35}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Role) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	IsRoot        bool                   `protobuf:"varint,9,opt,name=is_root,json=isRoot,proto3" json:"is_root,omitempty"`
	RoleId        string                 `protobuf:"bytes,10,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{36}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

func (x *User) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type ApiKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RoleId        string                 `protobuf:"bytes,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKey) Reset() {
	*x = ApiKey{}
	mi := &file_proto_iam_v0_api_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKey) ProtoMessage() {}

func (x *ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v0_api_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKey.ProtoReflect.Descriptor instead.
func (*ApiKey) Descriptor() ([]byte, []int) {
	return file_proto_iam_v0_api_proto_rawDescGZIP(), []int{37}
}

func (x *ApiKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKey) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApiKey) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ApiKey) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ApiKey) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *ApiKey) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ApiKey) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_proto_iam_v0_api_proto protoreflect.FileDescriptor

const file_proto_iam_v0_api_proto_rawDesc = "" +
	"\n" +
	"\x16proto/iam/v0/api.proto\x12\x11com.evrblk.iam.v0\"I\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"A\n" +
	"\x12CreateRoleResponse\x12+\n" +
	"\x04role\x18\x01 \x01(\v2\x17.com.evrblk.iam.v0.RoleR\x04role\")\n" +
	"\x0eGetRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\">\n" +
	"\x0fGetRoleResponse\x12+\n" +
	"\x04role\x18\x01 \x01(\v2\x17.com.evrblk.iam.v0.RoleR\x04role\"b\n" +
	"\x11UpdateRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"A\n" +
	"\x12UpdateRoleResponse\x12+\n" +
	"\x04role\x18\x01 \x01(\v2\x17.com.evrblk.iam.v0.RoleR\x04role\"S\n" +
	"\x10ListRolesRequest\x12)\n" +
	"\x10pagination_token\x18\x01 \x01(\tR\x0fpaginationToken\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xb2\x01\n" +
	"\x11ListRolesResponse\x12-\n" +
	"\x05roles\x18\x01 \x03(\v2\x17.com.evrblk.iam.v0.RoleR\x05roles\x122\n" +
	"\x15next_pagination_token\x18\x02 \x01(\tR\x13nextPaginationToken\x12:\n" +
	"\x19previous_pagination_token\x18\x03 \x01(\tR\x17previousPaginationToken\",\n" +
	"\x11DeleteRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\"\x14\n" +
	"\x12DeleteRoleResponse\"\x94\x01\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x17\n" +
	"\arole_id\x18\x05 \x01(\tR\x06roleId\"A\n" +
	"\x12CreateUserResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.com.evrblk.iam.v0.UserR\x04user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\">\n" +
	"\x0fGetUserResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.com.evrblk.iam.v0.UserR\x04user\",\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"A\n" +
	"\x12UpdateUserResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.com.evrblk.iam.v0.UserR\x04user\"S\n" +
	"\x10ListUsersRequest\x12)\n" +
	"\x10pagination_token\x18\x01 \x01(\tR\x0fpaginationToken\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xb2\x01\n" +
	"\x11ListUsersResponse\x12-\n" +
	"\x05users\x18\x01 \x03(\v2\x17.com.evrblk.iam.v0.UserR\x05users\x122\n" +
	"\x15next_pagination_token\x18\x02 \x01(\tR\x13nextPaginationToken\x12:\n" +
	"\x19previous_pagination_token\x18\x03 \x01(\tR\x17previousPaginationToken\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x14\n" +
	"\x12DeleteUserResponse\"\xf1\x02\n" +
	"\x13CreateApiKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x12=\n" +
	"\x04alfa\x18\x06 \x01(\v2'.com.evrblk.iam.v0.CreateAlfaKeyRequestH\x00R\x04alfa\x12@\n" +
	"\x05bravo\x18\a \x01(\v2(.com.evrblk.iam.v0.CreateBravoKeyRequestH\x00R\x05bravo\x12F\n" +
	"\acharlie\x18\b \x01(\v2*.com.evrblk.iam.v0.CreateCharlieKeyRequestH\x00R\acharlieB\n" +
	"\n" +
	"\bkey_type\"5\n" +
	"\x14CreateAlfaKeyRequest\x12\x1d\n" +
	"\n" +
	"public_pem\x18\x01 \x01(\tR\tpublicPem\"\x17\n" +
	"\x15CreateBravoKeyRequest\"\x19\n" +
	"\x17CreateCharlieKeyRequest\"M\n" +
	"\x14CreateApiKeyResponse\x125\n" +
	"\aapi_key\x18\x01 \x01(\v2\x1c.com.evrblk.iam.v0.NewApiKeyR\x06apiKey\"\x97\x03\n" +
	"\tNewApiKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12\x17\n" +
	"\arole_id\x18\x06 \x01(\tR\x06roleId\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\x03R\texpiresAt\x123\n" +
	"\x04alfa\x18\t \x01(\v2\x1d.com.evrblk.iam.v0.NewAlfaKeyH\x00R\x04alfa\x126\n" +
	"\x05bravo\x18\n" +
	" \x01(\v2\x1e.com.evrblk.iam.v0.NewBravoKeyH\x00R\x05bravo\x12<\n" +
	"\acharlie\x18\v \x01(\v2 .com.evrblk.iam.v0.NewCharlieKeyH\x00R\acharlieB\n" +
	"\n" +
	"\bkey_type\"+\n" +
	"\n" +
	"NewAlfaKey\x12\x1d\n" +
	"\n" +
	"public_pem\x18\x01 \x01(\tR\tpublicPem\"%\n" +
	"\vNewBravoKey\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\"\x0f\n" +
	"\rNewCharlieKey\"0\n" +
	"\x10GetApiKeyRequest\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x01 \x01(\tR\bapiKeyId\"G\n" +
	"\x11GetApiKeyResponse\x122\n" +
	"\aapi_key\x18\x01 \x01(\v2\x19.com.evrblk.iam.v0.ApiKeyR\x06apiKey\"U\n" +
	"\x12ListApiKeysRequest\x12)\n" +
	"\x10pagination_token\x18\x01 \x01(\tR\x0fpaginationToken\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xbb\x01\n" +
	"\x13ListApiKeysResponse\x124\n" +
	"\bapi_keys\x18\x01 \x03(\v2\x19.com.evrblk.iam.v0.ApiKeyR\aapiKeys\x122\n" +
	"\x15next_pagination_token\x18\x02 \x01(\tR\x13nextPaginationToken\x12:\n" +
	"\x19previous_pagination_token\x18\x03 \x01(\tR\x17previousPaginationToken\"3\n" +
	"\x13DeleteApiKeyRequest\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x01 \x01(\tR\bapiKeyId\"\x16\n" +
	"\x14DeleteApiKeyResponse\"\x8a\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"\xd2\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x17\n" +
	"\ais_root\x18\t \x01(\bR\x06isRoot\x12\x17\n" +
	"\arole_id\x18\n" +
	" \x01(\tR\x06roleId\"\xdd\x01\n" +
	"\x06ApiKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12\x17\n" +
	"\arole_id\x18\x06 \x01(\tR\x06roleId\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\x03R\texpiresAt2\x92\n" +
	"\n" +
	"\x06IamApi\x12[\n" +
	"\n" +
	"CreateRole\x12$.com.evrblk.iam.v0.CreateRoleRequest\x1a%.com.evrblk.iam.v0.CreateRoleResponse\"\x00\x12R\n" +
	"\aGetRole\x12!.com.evrblk.iam.v0.GetRoleRequest\x1a\".com.evrblk.iam.v0.GetRoleResponse\"\x00\x12[\n" +
	"\n" +
	"UpdateRole\x12$.com.evrblk.iam.v0.UpdateRoleRequest\x1a%.com.evrblk.iam.v0.UpdateRoleResponse\"\x00\x12X\n" +
	"\tListRoles\x12#.com.evrblk.iam.v0.ListRolesRequest\x1a$.com.evrblk.iam.v0.ListRolesResponse\"\x00\x12[\n" +
	"\n" +
	"DeleteRole\x12$.com.evrblk.iam.v0.DeleteRoleRequest\x1a%.com.evrblk.iam.v0.DeleteRoleResponse\"\x00\x12[\n" +
	"\n" +
	"CreateUser\x12$.com.evrblk.iam.v0.CreateUserRequest\x1a%.com.evrblk.iam.v0.CreateUserResponse\"\x00\x12R\n" +
	"\aGetUser\x12!.com.evrblk.iam.v0.GetUserRequest\x1a\".com.evrblk.iam.v0.GetUserResponse\"\x00\x12[\n" +
	"\n" +
	"UpdateUser\x12$.com.evrblk.iam.v0.UpdateUserRequest\x1a%.com.evrblk.iam.v0.UpdateUserResponse\"\x00\x12X\n" +
	"\tListUsers\x12#.com.evrblk.iam.v0.ListUsersRequest\x1a$.com.evrblk.iam.v0.ListUsersResponse\"\x00\x12[\n" +
	"\n" +
	"DeleteUser\x12$.com.evrblk.iam.v0.DeleteUserRequest\x1a%.com.evrblk.iam.v0.DeleteUserResponse\"\x00\x12a\n" +
	"\fCreateApiKey\x12&.com.evrblk.iam.v0.CreateApiKeyRequest\x1a'.com.evrblk.iam.v0.CreateApiKeyResponse\"\x00\x12X\n" +
	"\tGetApiKey\x12#.com.evrblk.iam.v0.GetApiKeyRequest\x1a$.com.evrblk.iam.v0.GetApiKeyResponse\"\x00\x12^\n" +
	"\vListApiKeys\x12%.com.evrblk.iam.v0.ListApiKeysRequest\x1a&.com.evrblk.iam.v0.ListApiKeysResponse\"\x00\x12a\n" +
	"\fDeleteApiKey\x12&.com.evrblk.iam.v0.DeleteApiKeyRequest\x1a'.com.evrblk.iam.v0.DeleteApiKeyResponse\"\x00B:Z&github.com/evrblk/evrblk-go/iam/v0;iam\xea\x02\x0fEvrblk::IAM::V0b\x06proto3"

var (
	file_proto_iam_v0_api_proto_rawDescOnce sync.Once
	file_proto_iam_v0_api_proto_rawDescData []byte
)

func file_proto_iam_v0_api_proto_rawDescGZIP() []byte {
	file_proto_iam_v0_api_proto_rawDescOnce.Do(func() {
		file_proto_iam_v0_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_iam_v0_api_proto_rawDesc), len(file_proto_iam_v0_api_proto_rawDesc)))
	})
	return file_proto_iam_v0_api_proto_rawDescData
}

var file_proto_iam_v0_api_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_proto_iam_v0_api_proto_goTypes = []any{
	(*CreateRoleRequest)(nil),       // 0: com.evrblk.iam.v0.CreateRoleRequest
	(*CreateRoleResponse)(nil),      // 1: com.evrblk.iam.v0.CreateRoleResponse
	(*GetRoleRequest)(nil),          // 2: com.evrblk.iam.v0.GetRoleRequest
	(*GetRoleResponse)(nil),         // 3: com.evrblk.iam.v0.GetRoleResponse
	(*UpdateRoleRequest)(nil),       // 4: com.evrblk.iam.v0.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),      // 5: com.evrblk.iam.v0.UpdateRoleResponse
	(*ListRolesRequest)(nil),        // 6: com.evrblk.iam.v0.ListRolesRequest
	(*ListRolesResponse)(nil),       // 7: com.evrblk.iam.v0.ListRolesResponse
	(*DeleteRoleRequest)(nil),       // 8: com.evrblk.iam.v0.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),      // 9: com.evrblk.iam.v0.DeleteRoleResponse
	(*CreateUserRequest)(nil),       // 10: com.evrblk.iam.v0.CreateUserRequest
	(*CreateUserResponse)(nil),      // 11: com.evrblk.iam.v0.CreateUserResponse
	(*GetUserRequest)(nil),          // 12: com.evrblk.iam.v0.GetUserRequest
	(*GetUserResponse)(nil),         // 13: com.evrblk.iam.v0.GetUserResponse
	(*UpdateUserRequest)(nil),       // 14: com.evrblk.iam.v0.UpdateUserRequest
	(*UpdateUserResponse)(nil),      // 15: com.evrblk.iam.v0.UpdateUserResponse
	(*ListUsersRequest)(nil),        // 16: com.evrblk.iam.v0.ListUsersRequest
	(*ListUsersResponse)(nil),       // 17: com.evrblk.iam.v0.ListUsersResponse
	(*DeleteUserRequest)(nil),       // 18: com.evrblk.iam.v0.DeleteUserRequest
	(*DeleteUserResponse)(nil),      // 19: com.evrblk.iam.v0.DeleteUserResponse
	(*CreateApiKeyRequest)(nil),     // 20: com.evrblk.iam.v0.CreateApiKeyRequest
	(*CreateAlfaKeyRequest)(nil),    // 21: com.evrblk.iam.v0.CreateAlfaKeyRequest
	(*CreateBravoKeyRequest)(nil),   // 22: com.evrblk.iam.v0.CreateBravoKeyRequest
	(*CreateCharlieKeyRequest)(nil), // 23: com.evrblk.iam.v0.CreateCharlieKeyRequest
	(*CreateApiKeyResponse)(nil),    // 24: com.evrblk.iam.v0.CreateApiKeyResponse
	(*NewApiKey)(nil),               // 25: com.evrblk.iam.v0.NewApiKey
	(*NewAlfaKey)(nil),              // 26: com.evrblk.iam.v0.NewAlfaKey
	(*NewBravoKey)(nil),             // 27: com.evrblk.iam.v0.NewBravoKey
	(*NewCharlieKey)(nil),           // 28: com.evrblk.iam.v0.NewCharlieKey
	(*GetApiKeyRequest)(nil),        // 29: com.evrblk.iam.v0.GetApiKeyRequest
	(*GetApiKeyResponse)(nil),       // 30: com.evrblk.iam.v0.GetApiKeyResponse
	(*ListApiKeysRequest)(nil),      // 31: com.evrblk.iam.v0.ListApiKeysRequest
	(*ListApiKeysResponse)(nil),     // 32: com.evrblk.iam.v0.ListApiKeysResponse
	(*DeleteApiKeyRequest)(nil),     // 33: com.evrblk.iam.v0.DeleteApiKeyRequest
	(*DeleteApiKeyResponse)(nil),    // 34: com.evrblk.iam.v0.DeleteApiKeyResponse
	(*Role)(nil),                    // 35: com.evrblk.iam.v0.Role
	(*User)(nil),                    // 36: com.evrblk.iam.v0.User
	(*ApiKey)(nil),                  // 37: com.evrblk.iam.v0.ApiKey
}
var file_proto_iam_v0_api_proto_depIdxs = []int32{
	35, // 0: com.evrblk.iam.v0.CreateRoleResponse.role:type_name -> com.evrblk.iam.v0.Role
	35, // 1: com.evrblk.iam.v0.GetRoleResponse.role:type_name -> com.evrblk.iam.v0.Role
	35, // 2: com.evrblk.iam.v0.UpdateRoleResponse.role:type_name -> com.evrblk.iam.v0.Role
	35, // 3: com.evrblk.iam.v0.ListRolesResponse.roles:type_name -> com.evrblk.iam.v0.Role
	36, // 4: com.evrblk.iam.v0.CreateUserResponse.user:type_name -> com.evrblk.iam.v0.User
	36, // 5: com.evrblk.iam.v0.GetUserResponse.user:type_name -> com.evrblk.iam.v0.User
	36, // 6: com.evrblk.iam.v0.UpdateUserResponse.user:type_name -> com.evrblk.iam.v0.User
	36, // 7: com.evrblk.iam.v0.ListUsersResponse.users:type_name -> com.evrblk.iam.v0.User
	21, // 8: com.evrblk.iam.v0.CreateApiKeyRequest.alfa:type_name -> com.evrblk.iam.v0.CreateAlfaKeyRequest
	22, // 9: com.evrblk.iam.v0.CreateApiKeyRequest.bravo:type_name -> com.evrblk.iam.v0.CreateBravoKeyRequest
	23, // 10: com.evrblk.iam.v0.CreateApiKeyRequest.charlie:type_name -> com.evrblk.iam.v0.CreateCharlieKeyRequest
	25, // 11: com.evrblk.iam.v0.CreateApiKeyResponse.api_key:type_name -> com.evrblk.iam.v0.NewApiKey
	26, // 12: com.evrblk.iam.v0.NewApiKey.alfa:type_name -> com.evrblk.iam.v0.NewAlfaKey
	27, // 13: com.evrblk.iam.v0.NewApiKey.bravo:type_name -> com.evrblk.iam.v0.NewBravoKey
	28, // 14: com.evrblk.iam.v0.NewApiKey.charlie:type_name -> com.evrblk.iam.v0.NewCharlieKey
	37, // 15: com.evrblk.iam.v0.GetApiKeyResponse.api_key:type_name -> com.evrblk.iam.v0.ApiKey
	37, // 16: com.evrblk.iam.v0.ListApiKeysResponse.api_keys:type_name -> com.evrblk.iam.v0.ApiKey
	0,  // 17: com.evrblk.iam.v0.IamApi.CreateRole:input_type -> com.evrblk.iam.v0.CreateRoleRequest
	2,  // 18: com.evrblk.iam.v0.IamApi.GetRole:input_type -> com.evrblk.iam.v0.GetRoleRequest
	4,  // 19: com.evrblk.iam.v0.IamApi.UpdateRole:input_type -> com.evrblk.iam.v0.UpdateRoleRequest
	6,  // 20: com.evrblk.iam.v0.IamApi.ListRoles:input_type -> com.evrblk.iam.v0.ListRolesRequest
	8,  // 21: com.evrblk.iam.v0.IamApi.DeleteRole:input_type -> com.evrblk.iam.v0.DeleteRoleRequest
	10, // 22: com.evrblk.iam.v0.IamApi.CreateUser:input_type -> com.evrblk.iam.v0.CreateUserRequest
	12, // 23: com.evrblk.iam.v0.IamApi.GetUser:input_type -> com.evrblk.iam.v0.GetUserRequest
	14, // 24: com.evrblk.iam.v0.IamApi.UpdateUser:input_type -> com.evrblk.iam.v0.UpdateUserRequest
	16, // 25: com.evrblk.iam.v0.IamApi.ListUsers:input_type -> com.evrblk.iam.v0.ListUsersRequest
	18, // 26: com.evrblk.iam.v0.IamApi.DeleteUser:input_type -> com.evrblk.iam.v0.DeleteUserRequest
	20, // 27: com.evrblk.iam.v0.IamApi.CreateApiKey:input_type -> com.evrblk.iam.v0.CreateApiKeyRequest
	29, // 28: com.evrblk.iam.v0.IamApi.GetApiKey:input_type -> com.evrblk.iam.v0.GetApiKeyRequest
	31, // 29: com.evrblk.iam.v0.IamApi.ListApiKeys:input_type -> com.evrblk.iam.v0.ListApiKeysRequest
	33, // 30: com.evrblk.iam.v0.IamApi.DeleteApiKey:input_type -> com.evrblk.iam.v0.DeleteApiKeyRequest
	1,  // 31: com.evrblk.iam.v0.IamApi.CreateRole:output_type -> com.evrblk.iam.v0.CreateRoleResponse
	3,  // 32: com.evrblk.iam.v0.IamApi.GetRole:output_type -> com.evrblk.iam.v0.GetRoleResponse
	5,  // 33: com.evrblk.iam.v0.IamApi.UpdateRole:output_type -> com.evrblk.iam.v0.UpdateRoleResponse
	7,  // 34: com.evrblk.iam.v0.IamApi.ListRoles:output_type -> com.evrblk.iam.v0.ListRolesResponse
	9,  // 35: com.evrblk.iam.v0.IamApi.DeleteRole:output_type -> com.evrblk.iam.v0.DeleteRoleResponse
	11, // 36: com.evrblk.iam.v0.IamApi.CreateUser:output_type -> com.evrblk.iam.v0.CreateUserResponse
	13, // 37: com.evrblk.iam.v0.IamApi.GetUser:output_type -> com.evrblk.iam.v0.GetUserResponse
	15, // 38: com.evrblk.iam.v0.IamApi.UpdateUser:output_type -> com.evrblk.iam.v0.UpdateUserResponse
	17, // 39: com.evrblk.iam.v0.IamApi.ListUsers:output_type -> com.evrblk.iam.v0.ListUsersResponse
	19, // 40: com.evrblk.iam.v0.IamApi.DeleteUser:output_type -> com.evrblk.iam.v0.DeleteUserResponse
	24, // 41: com.evrblk.iam.v0.IamApi.CreateApiKey:output_type -> com.evrblk.iam.v0.CreateApiKeyResponse
	30, // 42: com.evrblk.iam.v0.IamApi.GetApiKey:output_type -> com.evrblk.iam.v0.GetApiKeyResponse
	32, // 43: com.evrblk.iam.v0.IamApi.ListApiKeys:output_type -> com.evrblk.iam.v0.ListApiKeysResponse
	34, // 44: com.evrblk.iam.v0.IamApi.DeleteApiKey:output_type -> com.evrblk.iam.v0.DeleteApiKeyResponse
	31, // [31:45] is the sub-list for method output_type
	17, // [17:31] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_iam_v0_api_proto_init() }
func file_proto_iam_v0_api_proto_init() {
	if File_proto_iam_v0_api_proto != nil {
		return
	}
	file_proto_iam_v0_api_proto_msgTypes[20].OneofWrappers = []any{
		(*CreateApiKeyRequest_Alfa)(nil),
		(*CreateApiKeyRequest_Bravo)(nil),
		(*CreateApiKeyRequest_Charlie)(nil),
	}
	file_proto_iam_v0_api_proto_msgTypes[25].OneofWrappers = []any{
		(*NewApiKey_Alfa)(nil),
		(*NewApiKey_Bravo)(nil),
		(*NewApiKey_Charlie)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_iam_v0_api_proto_rawDesc), len(file_proto_iam_v0_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_iam_v0_api_proto_goTypes,
		DependencyIndexes: file_proto_iam_v0_api_proto_depIdxs,
		MessageInfos:      file_proto_iam_v0_api_proto_msgTypes,
	}.Build()
	File_proto_iam_v0_api_proto = out.File
	file_proto_iam_v0_api_proto_goTypes = nil
	file_proto_iam_v0_api_proto_depIdxs = nil
}
