// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: evrblkapis/myaccount/preview/api.proto

package myaccount

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MyAccountPreviewApi_GetAccount_FullMethodName = "/com.evrblk.myaccount.preview.MyAccountPreviewApi/GetAccount"
)

// MyAccountPreviewApiClient is the client API for MyAccountPreviewApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyAccountPreviewApiClient interface {
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
}

type myAccountPreviewApiClient struct {
	cc grpc.ClientConnInterface
}

func NewMyAccountPreviewApiClient(cc grpc.ClientConnInterface) MyAccountPreviewApiClient {
	return &myAccountPreviewApiClient{cc}
}

func (c *myAccountPreviewApiClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, MyAccountPreviewApi_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyAccountPreviewApiServer is the server API for MyAccountPreviewApi service.
// All implementations must embed UnimplementedMyAccountPreviewApiServer
// for forward compatibility.
type MyAccountPreviewApiServer interface {
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	mustEmbedUnimplementedMyAccountPreviewApiServer()
}

// UnimplementedMyAccountPreviewApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMyAccountPreviewApiServer struct{}

func (UnimplementedMyAccountPreviewApiServer) GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedMyAccountPreviewApiServer) mustEmbedUnimplementedMyAccountPreviewApiServer() {}
func (UnimplementedMyAccountPreviewApiServer) testEmbeddedByValue()                             {}

// UnsafeMyAccountPreviewApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyAccountPreviewApiServer will
// result in compilation errors.
type UnsafeMyAccountPreviewApiServer interface {
	mustEmbedUnimplementedMyAccountPreviewApiServer()
}

func RegisterMyAccountPreviewApiServer(s grpc.ServiceRegistrar, srv MyAccountPreviewApiServer) {
	// If the following call pancis, it indicates UnimplementedMyAccountPreviewApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MyAccountPreviewApi_ServiceDesc, srv)
}

func _MyAccountPreviewApi_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyAccountPreviewApiServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyAccountPreviewApi_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyAccountPreviewApiServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MyAccountPreviewApi_ServiceDesc is the grpc.ServiceDesc for MyAccountPreviewApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyAccountPreviewApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.evrblk.myaccount.preview.MyAccountPreviewApi",
	HandlerType: (*MyAccountPreviewApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _MyAccountPreviewApi_GetAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evrblkapis/myaccount/preview/api.proto",
}
