syntax = "proto3";

package com.evrblk.grackle.v1beta;

option go_package = "github.com/evrblk/evrblk-go/grackle/v1beta;grackle";
option ruby_package = "Evrblk::Grackle::V1Beta";

service GrackleApi {
  rpc CreateNamespace(CreateNamespaceRequest) returns (CreateNamespaceResponse) {}
  rpc ListNamespaces(ListNamespacesRequest) returns (ListNamespacesResponse) {}
  rpc GetNamespace(GetNamespaceRequest) returns (GetNamespaceResponse) {}
  rpc DeleteNamespace(DeleteNamespaceRequest) returns (DeleteNamespaceResponse) {}
  rpc UpdateNamespace(UpdateNamespaceRequest) returns (UpdateNamespaceResponse) {}

  rpc CreateSemaphore(CreateSemaphoreRequest) returns (CreateSemaphoreResponse) {}
  rpc ListSemaphores(ListSemaphoresRequest) returns (ListSemaphoresResponse) {}
  rpc GetSemaphore(GetSemaphoreRequest) returns (GetSemaphoreResponse) {}
  rpc AcquireSemaphore(AcquireSemaphoreRequest) returns (AcquireSemaphoreResponse) {}
  rpc ReleaseSemaphore(ReleaseSemaphoreRequest) returns (ReleaseSemaphoreResponse) {}
  rpc UpdateSemaphore(UpdateSemaphoreRequest) returns (UpdateSemaphoreResponse) {}
  rpc DeleteSemaphore(DeleteSemaphoreRequest) returns (DeleteSemaphoreResponse) {}
  rpc ListSemaphoreHolders(ListSemaphoreHoldersRequest) returns (ListSemaphoreHoldersResponse) {}
  rpc CreateSemaphoreLease(CreateSemaphoreLeaseRequest) returns (CreateSemaphoreLeaseResponse) {}
  rpc RevokeSemaphoreLease(RevokeSemaphoreLeaseRequest) returns (RevokeSemaphoreLeaseResponse) {}
  rpc RefreshSemaphoreLease(RefreshSemaphoreLeaseRequest) returns (RefreshSemaphoreLeaseResponse) {}
  rpc ListSemaphoreLeases(ListSemaphoreLeasesRequest) returns (ListSemaphoreLeasesResponse) {}
  rpc GetSemaphoreLease(GetSemaphoreLeaseRequest) returns (GetSemaphoreLeaseResponse) {}

  rpc CreateWaitGroup(CreateWaitGroupRequest) returns (CreateWaitGroupResponse) {}
  rpc ListWaitGroups(ListWaitGroupsRequest) returns (ListWaitGroupsResponse) {}
  rpc GetWaitGroup(GetWaitGroupRequest) returns (GetWaitGroupResponse) {}
  rpc DeleteWaitGroup(DeleteWaitGroupRequest) returns (DeleteWaitGroupResponse) {}
  rpc AddJobsToWaitGroup(AddJobsToWaitGroupRequest) returns (AddJobsToWaitGroupResponse) {}
  rpc CompleteJobsFromWaitGroup(CompleteJobsFromWaitGroupRequest) returns (CompleteJobsFromWaitGroupResponse) {}
  rpc ListWaitGroupCompletedJobs(ListWaitGroupCompletedJobsRequest) returns (ListWaitGroupCompletedJobsResponse) {}
  rpc WaitForWaitGroup(WaitForWaitGroupRequest) returns (WaitForWaitGroupResponse) {}

  rpc AcquireLock(AcquireLockRequest) returns (AcquireLockResponse) {}
  rpc ReleaseLock(ReleaseLockRequest) returns (ReleaseLockResponse) {}
  rpc GetLock(GetLockRequest) returns (GetLockResponse) {}
  rpc DeleteLock(DeleteLockRequest) returns (DeleteLockResponse) {}
  rpc ListLocks(ListLocksRequest) returns (ListLocksResponse) {}
  rpc CreateLockLease(CreateLockLeaseRequest) returns (CreateLockLeaseResponse) {}
  rpc RevokeLockLease(RevokeLockLeaseRequest) returns (RevokeLockLeaseResponse) {}
  rpc RefreshLockLease(RefreshLockLeaseRequest) returns (RefreshLockLeaseResponse) {}
  rpc ListLockLeases(ListLockLeasesRequest) returns (ListLockLeasesResponse) {}
  rpc GetLockLease(GetLockLeaseRequest) returns (GetLockLeaseResponse) {}

  rpc CreateBarrier(CreateBarrierRequest) returns (CreateBarrierResponse) {}
  rpc ListBarriers(ListBarriersRequest) returns (ListBarriersResponse) {}
  rpc GetBarrier(GetBarrierRequest) returns (GetBarrierResponse) {}
  rpc DeleteBarrier(DeleteBarrierRequest) returns (DeleteBarrierResponse) {}
  rpc UpdateBarrier(UpdateBarrierRequest) returns (UpdateBarrierResponse) {}
  rpc ArriveAtBarrier(ArriveAtBarrierRequest) returns (ArriveAtBarrierResponse) {}
  rpc WaitAtBarrier(WaitAtBarrierRequest) returns (WaitAtBarrierResponse) {}
  rpc ListBarrierParticipants(ListBarrierParticipantsRequest) returns (ListBarrierParticipantsResponse) {}
}

message CreateNamespaceRequest {
  string name = 1;
  string description = 2;
  map<string, string> metadata = 3;
}

message CreateNamespaceResponse {
  Namespace namespace = 1;
}

message ListNamespacesRequest {
  string pagination_token = 1;
  int32 limit = 2;
}

message ListNamespacesResponse {
  repeated Namespace namespaces = 1;
  string next_pagination_token = 2;
  string previous_pagination_token = 3;
}

message GetNamespaceRequest {
  string namespace_name = 1;
}

message GetNamespaceResponse {
  Namespace namespace = 1;
}

message DeleteNamespaceRequest {
  string namespace_name = 1;
}

message DeleteNamespaceResponse {}

message UpdateNamespaceRequest {
  string namespace_name = 1;
  string description = 2;
  map<string, string> metadata = 3;
}

message UpdateNamespaceResponse {
  Namespace namespace = 1;
}

message CreateSemaphoreRequest {
  string namespace_name = 1;
  string semaphore_name = 2;
  string description = 3;
  uint64 permits = 4;
  map<string, string> metadata = 5;
}

message CreateSemaphoreResponse {
  Semaphore semaphore = 1;
}

message ListSemaphoresRequest {
  string namespace_name = 1;
  string pagination_token = 2;
  int32 limit = 3;
}

message ListSemaphoresResponse {
  repeated Semaphore semaphores = 1;
  string next_pagination_token = 2;
  string previous_pagination_token = 3;
}

message GetSemaphoreRequest {
  string namespace_name = 1;
  string semaphore_name = 2;
}

message GetSemaphoreResponse {
  Semaphore semaphore = 1;
}

message AcquireSemaphoreRequest {
  string namespace_name = 1;
  string semaphore_name = 2;
  string lease_id = 3;
  uint64 weight = 4;
  int32 timeout_seconds = 5;
  map<string, string> metadata = 6;
}

message AcquireSemaphoreResponse {
  Semaphore semaphore = 1;
  bool success = 2;
}

message ReleaseSemaphoreRequest {
  string namespace_name = 1;
  string semaphore_name = 2;
  string lease_id = 3;
}

message ReleaseSemaphoreResponse {
  Semaphore semaphore = 1;
}

message UpdateSemaphoreRequest {
  string namespace_name = 1;
  string semaphore_name = 2;
  string description = 3;
  uint64 permits = 4;
  map<string, string> metadata = 5;
}

message UpdateSemaphoreResponse {
  Semaphore semaphore = 1;
}

message DeleteSemaphoreRequest {
  string namespace_name = 1;
  string semaphore_name = 2;
}

message DeleteSemaphoreResponse {}

message ListSemaphoreHoldersRequest {
  string namespace_name = 1;
  string semaphore_name = 2;
  string pagination_token = 3;
  int32 limit = 4;
}

message ListSemaphoreHoldersResponse {
  repeated SemaphoreHolder holders = 1;
  string next_pagination_token = 2;
  string previous_pagination_token = 3;
}

message CreateSemaphoreLeaseRequest {
  string namespace_name = 1;
  string process_id = 2;
  uint64 ttl_seconds = 3;
  map<string, string> metadata = 4;
}

message CreateSemaphoreLeaseResponse {
  Lease lease = 1;
}

message RevokeSemaphoreLeaseRequest {
  string namespace_name = 1;
  string lease_id = 2;
}

message RevokeSemaphoreLeaseResponse {}

message RefreshSemaphoreLeaseRequest {
  string namespace_name = 1;
  string lease_id = 2;
  uint64 ttl_seconds = 3;
}

message RefreshSemaphoreLeaseResponse {
  Lease lease = 1;
}

message ListSemaphoreLeasesRequest {
  string namespace_name = 1;
  string pagination_token = 2;
  int32 limit = 3;
}

message ListSemaphoreLeasesResponse {
  repeated Lease leases = 1;
  string next_pagination_token = 2;
  string previous_pagination_token = 3;
}

message GetSemaphoreLeaseRequest {
  string namespace_name = 1;
  string lease_id = 2;
}

message GetSemaphoreLeaseResponse {
  Lease lease = 1;
}

message Lease {
  string lease_id = 1;
  string process_id = 2;
  int64 created_at = 3;
  int64 expires_at = 4;
  map<string, string> metadata = 5;
}

message Semaphore {
  string name = 1;
  string description = 2;
  int64 created_at = 3;
  int64 updated_at = 4;
  uint64 version = 5;
  uint64 permits = 6;
  uint64 active_holds = 7;
  uint64 active_holders_count = 8;
  map<string, string> metadata = 9;
}

message SemaphoreHolder {
  string lease_id = 1;
  int64 locked_at = 2;
  uint64 weight = 3;
  map<string, string> metadata = 4;
}

message CreateWaitGroupRequest {
  string namespace_name = 1;
  string wait_group_name = 2;
  string description = 3;
  uint64 counter = 4;
  int64 expires_at = 5;
  map<string, string> metadata = 6;
}

message CreateWaitGroupResponse {
  WaitGroup wait_group = 1;
}

message ListWaitGroupsRequest {
  string namespace_name = 1;
  string pagination_token = 2;
  int32 limit = 3;
}

message ListWaitGroupsResponse {
  repeated WaitGroup wait_groups = 1;
  string next_pagination_token = 2;
  string previous_pagination_token = 3;
}

message GetWaitGroupRequest {
  string namespace_name = 1;
  string wait_group_name = 2;
}

message GetWaitGroupResponse {
  WaitGroup wait_group = 1;
}

message DeleteWaitGroupRequest {
  string namespace_name = 1;
  string wait_group_name = 2;
}

message DeleteWaitGroupResponse {}

message AddJobsToWaitGroupRequest {
  string namespace_name = 1;
  string wait_group_name = 2;
  uint64 counter = 3;
}

message AddJobsToWaitGroupResponse {
  WaitGroup wait_group = 1;
}

message CompleteJobsFromWaitGroupRequest {
  string namespace_name = 1;
  string wait_group_name = 2;
  repeated CompleteJobRequest jobs = 3;
}

message CompleteJobRequest {
  string job_id = 1;
  map<string, string> metadata = 2;
}

message CompleteJobsFromWaitGroupResponse {
  WaitGroup wait_group = 1;
}

message ListWaitGroupCompletedJobsRequest {
  string namespace_name = 1;
  string wait_group_name = 2;
  string pagination_token = 3;
  int32 limit = 4;
}

message ListWaitGroupCompletedJobsResponse {
  repeated WaitGroupJob jobs = 1;
  string next_pagination_token = 2;
  string previous_pagination_token = 3;
}

message WaitForWaitGroupRequest {
  string namespace_name = 1;
  string wait_group_name = 2;
  int32 timeout_seconds = 3;
}

message WaitForWaitGroupResponse {
  WaitGroup wait_group = 1;
  bool completed = 2;
  bool timed_out = 3;
}

message WaitGroup {
  string name = 1;
  string description = 2;
  int64 created_at = 3;
  int64 updated_at = 4;
  uint64 version = 5;
  int64 expires_at = 6;
  uint64 counter = 7;
  uint64 completed = 8;
  map<string, string> metadata = 9;
}

message WaitGroupJob {
  string job_id = 1;
  int64 completed_at = 2;
  map<string, string> metadata = 3;
}

message AcquireLockRequest {
  string namespace_name = 1;
  string lock_name = 2;
  bool exclusive = 3;
  string lease_id = 4;
  int32 timeout_seconds = 5;
  map<string, string> metadata = 6;
}

message AcquireLockResponse {
  Lock lock = 1;
  bool success = 2;
}

message ReleaseLockRequest {
  string namespace_name = 1;
  string lock_name = 2;
  string lease_id = 3;
}

message ReleaseLockResponse {
  Lock lock = 1;
}

message GetLockRequest {
  string namespace_name = 1;
  string lock_name = 2;
}

message GetLockResponse {
  Lock lock = 1;
}

message DeleteLockRequest {
  string namespace_name = 1;
  string lock_name = 2;
}

message DeleteLockResponse {}

message ListLocksRequest {
  string namespace_name = 1;
  string pagination_token = 2;
  int32 limit = 3;
}

message ListLocksResponse {
  repeated Lock locks = 1;
  string next_pagination_token = 2;
  string previous_pagination_token = 3;
}

message CreateLockLeaseRequest {
  string namespace_name = 1;
  string process_id = 2;
  uint64 ttl_seconds = 3;
  map<string, string> metadata = 4;
}

message CreateLockLeaseResponse {
  Lease lease = 1;
}

message RevokeLockLeaseRequest {
  string namespace_name = 1;
  string lease_id = 2;
}

message RevokeLockLeaseResponse {}

message RefreshLockLeaseRequest {
  string namespace_name = 1;
  string lease_id = 2;
  uint64 ttl_seconds = 3;
}

message RefreshLockLeaseResponse {
  Lease lease = 1;
}

message ListLockLeasesRequest {
  string namespace_name = 1;
  string pagination_token = 2;
  int32 limit = 3;
}

message ListLockLeasesResponse {
  repeated Lease leases = 1;
  string next_pagination_token = 2;
  string previous_pagination_token = 3;
}

message GetLockLeaseRequest {
  string namespace_name = 1;
  string lease_id = 2;
}

message GetLockLeaseResponse {
  Lease lease = 1;
}

message Lock {
  string name = 1;
  LockState state = 2;
  int64 locked_at = 3;
  repeated LockHolder lock_holders = 4;
}

message LockHolder {
  string lease_id = 1;
  int64 locked_at = 2;
  map<string, string> metadata = 3;
}

enum LockState {
  UNLOCKED = 0;
  SHARED_LOCKED = 1;
  EXCLUSIVE_LOCKED = 2;
}

message Namespace {
  string name = 1;
  string description = 2;
  int64 created_at = 3;
  int64 updated_at = 4;
  uint64 version = 5;
  map<string, string> metadata = 6;
}

message CreateBarrierRequest {
  string namespace_name = 1;
  string barrier_name = 2;
  string description = 3;
  uint64 expected_processes = 4;
  int64 expires_at = 8;
  map<string, string> metadata = 9;
}

message CreateBarrierResponse {
  Barrier barrier = 1;
}

message ListBarriersRequest {
  string namespace_name = 1;
  string pagination_token = 2;
  int32 limit = 3;
}

message ListBarriersResponse {
  repeated Barrier barriers = 1;
  string next_pagination_token = 2;
  string previous_pagination_token = 3;
}

message GetBarrierRequest {
  string namespace_name = 1;
  string barrier_name = 2;
}

message GetBarrierResponse {
  Barrier barrier = 1;
}

message DeleteBarrierRequest {
  string namespace_name = 1;
  string barrier_name = 2;
}

message DeleteBarrierResponse {}

message UpdateBarrierRequest {
  string namespace_name = 1;
  string barrier_name = 2;
  string description = 3;
  uint64 expected_processes = 4;
  map<string, string> metadata = 5;
}

message UpdateBarrierResponse {
  Barrier barrier = 1;
}

message ArriveAtBarrierRequest {
  string namespace_name = 1;
  string barrier_name = 2;
  string process_id = 3;
  uint64 expected_generation = 4;
  map<string, string> metadata = 5;
}

message ArriveAtBarrierResponse {
  Barrier barrier = 1;
  bool all_arrived = 2;
  uint64 next_generation = 3;
}

message WaitAtBarrierRequest {
  string namespace_name = 1;
  string barrier_name = 2;
  uint64 expected_generation = 3;
  int32 timeout_seconds = 4;
}

message WaitAtBarrierResponse {
  Barrier barrier = 1;
  bool all_arrived = 2;
  uint64 next_generation = 3;
  bool timed_out = 4;
}

message ListBarrierParticipantsRequest {
  string namespace_name = 1;
  string barrier_name = 2;
  uint64 generation = 3;
  string pagination_token = 4;
  int32 limit = 5;
}

message ListBarrierParticipantsResponse {
  repeated BarrierParticipant participants = 1;
  string next_pagination_token = 2;
  string previous_pagination_token = 3;
}

message Barrier {
  string name = 1;
  string description = 2;
  uint64 expected_processes = 3;
  uint64 arrived_processes = 4;
  uint64 generation = 5;
  int64 created_at = 6;
  int64 updated_at = 7;
  uint64 version = 8;
  map<string, string> metadata = 9;
}

message BarrierParticipant {
  string process_id = 1;
  int64 arrived_at = 2;
  map<string, string> metadata = 3;
}
